In [1]:
import uproot
import numpy as np

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
from mpl_toolkits.mplot3d import Axes3D

import h5py as h5
import math
import os

import pandas as pd
import plotly.graph_objects as go

import plotly.express as px
import sys

from ipywidgets import interact

In [2]:
SOFTWARE_DIR = '/global/homes/k/kjvocker/spine/src' # Path to software install
DATA_DIR = '/global/homes/k/kjvocker/data/'
Mx2_DIR = "/global/cfs/cdirs/dune/www/data/2x2/simulation/productions/MiniRun5_1E19_RHC/MiniRun5_1E19_RHC.minerva/DST/0000000/"
SPINE_DIR = "/global/cfs/cdirs/dune/www/data/2x2/simulation/productions/MiniRun6.4_1E19_RHC/MiniRun6.4_1E19_RHC.spine_v2/MLRECO_SPINE/0000000/"

TMS_DIR = "/global/cfs/cdirs/dunepro/people/abooth/nd-production/output/MiniProdN5/run-tms-reco/MiniProdN5p1_NDComplex_FHC.tmsreco.full.sanddrift/TMSRECO/0002000/"
NDLAr_DIR = "/global/cfs/cdirs/dunepro/people/abooth/nd-production/output/MiniProdN5/run-mlreco/MiniProdN5p1_NDComplex_FHC.spine.full.sanddrift/MLRECO_SPINE/0002000/"

filenum = 471

TMS_file = f"{TMS_DIR}MiniProdN5p1_NDComplex_FHC.tmsreco.full.sanddrift.0002{filenum}.TMSRECO.root"
SPINE_file = f"{NDLAr_DIR}MiniProdN5p1_NDComplex_FHC.spine.full.sanddrift.0002{filenum}.MLRECO_SPINE.hdf5"

# Set software directory
sys.path.append(SOFTWARE_DIR)
import yaml
from spine.driver import Driver

Welcome to JupyROOT 6.26/16

## Colour Palette

In [3]:
NDLAr_colour = '#e63946'

# List 1: Accessible Base (Strong & Distinct)
strong_colours = [
    '#E69F00', # Orange
    '#0072B2', # Deep Blue
    '#009E73', # Bluish Green
    '#CC79A7', # Reddish Purple
    '#D55E00', # Vermillion
    '#56B4E9', # Sky Blue
    '#F0E442'  # Yellow
]

# List 2: Accessible Tint (Lighter "Shadow" Versions)
light_colours = [
    '#f0c975', # Light Orange
    '#70b1d9', # Pale Blue
    '#7ecdb9', # Light Green
    '#e0adc9', # Light Orchid
    '#e8a176', # Light Salmon
    '#a2d9f7', # Very Light Blue
    '#f7f2a1'  # Pale Yellow
]

## Create ND-LAr and TMS Geometry

In [4]:
# Geometry defined in TMS_Constants.h:

#  // Approximate starting and end positions of TMS detector in geometry for plotting hits, in {x,y,z}
#  // in mm by default!
#  const double TMS_Start[] = {-4000, -3500, 11000};
#  const double TMS_End[] = {4000, 500, 19000};

# const double TMS_Double_End = 18502.5;  //this is still with problems in the geometry!!!
# const double TMS_Thin_Start = 11177.5;  //start of TMS at 1116 cm - bar thickness / 2 (8 mm) = 11160 - 8 = 11152 mm
# const double TMS_Start_Exact[] = {-3730, -3702.23, TMS_Thin_Start};
# const double TMS_End_Exact[] = {3730, 997.77, TMS_Double_End};

#  // From scanning all hits x,y,z position in the LAr active volume
#  const double LAr_Start_Exact[] = {-3478.48, -2166.71, 4179.24};
#  const double LAr_End_Exact[] = {3478.48, 829.282, 9135.88};

In [5]:
def plot_box(fig, x_min, x_max, y_min, y_max, z_min, z_max, color, name):
    # This path visits every corner of a box in one continuous line.
    # We use 'None' to jump between disconnected edges.
    x = [x_min, x_max, x_max, x_min, x_min, x_min, x_max, x_max, x_min, x_min, None, x_max, x_max, None, x_min, x_min, None, x_max, x_max]
    y = [y_min, y_min, y_max, y_max, y_min, y_min, y_min, y_max, y_max, y_min, None, y_min, y_min, None, y_max, y_max, None, y_max, y_max]
    z = [z_min, z_min, z_min, z_min, z_min, z_max, z_max, z_max, z_max, z_max, None, z_min, z_max, None, z_min, z_max, None, z_min, z_max]

    fig.add_trace(
        go.Scatter3d(
            x=x, y=y, z=z,
            mode="lines",
            line=dict(color=color, width=3),
            name=name,
            showlegend=True
        )
    )

## Class to pull data from TMS file

In [6]:
class TMSData:
    def __init__(self, filename):
        self.file = uproot.open(filename)

        # Truth Info
        self.EventNo = self.file["Truth_Info"]["EventNo"].array(library="np")
        self.SpillNo = self.file["Truth_Info"]["SpillNo"].array(library="np")
        self.RunNo = self.file["Truth_Info"]["RunNo"].array(library="np")
        self.Interation = self.file["Truth_Info"]["Interaction"].array(library="np")
        
        self.TruthInfoIndex = self.file["Truth_Info"]["TruthInfoIndex"].array(library="np")
        self.TruthInfoNSlices = self.file["Truth_Info"]["TruthInfoNSlices"].array(library="np")
        self.nPrimaryVertices = self.file["Truth_Info"]["nPrimaryVertices"].array(library="np")
        self.nParticles = self.file["Truth_Info"]["nParticles"].array(library="np")
        self.MuonVertex = self.file["Truth_Info"]["Muon_Vertex"].array(library="np")
        self.VertexIdOfMostEnergyInEvent = self.file["Truth_Info"]["VertexIdOfMostEnergyInEvent"].array(library="np")
        self.RecoTrackN = self.file["Truth_Info"]["RecoTrackN"].array(library="np")

        self.NeutrinoX4 = self.file["Truth_Info"]["NeutrinoX4"].array(library="np")

        self.RecoTrackPrimaryParticleIndex = self.file["Truth_Info"]["RecoTrackPrimaryParticleIndex"].array(library="np")
        self.RecoTrackPrimaryParticleTruePositionTrackStart = self.file["Truth_Info"]["RecoTrackPrimaryParticleTruePositionTrackStart"].array(library="np")
        self.RecoTrackPrimaryParticleTruePositionTrackEnd = self.file["Truth_Info"]["RecoTrackPrimaryParticleTruePositionTrackEnd"].array(library="np")
        self.RecoTrackTrueHitPosition = self.file["Truth_Info"]["RecoTrackTrueHitPosition"].array(library="np")
        self.RecoTrackPrimaryParticlePDG = self.file["Truth_Info"]["RecoTrackPrimaryParticlePDG"].array(library="np")
        self.RecoTrackPrimaryParticleTruePositionStart = self.file["Truth_Info"]["RecoTrackPrimaryParticleTruePositionStart"].array(library="np")
        self.RecoTrackPrimaryParticleTruePositionEnd = self.file["Truth_Info"]["RecoTrackPrimaryParticleTruePositionEnd"].array(library="np")
        self.RecoTrackPrimaryParticleTruePositionEnteringTMS = self.file["Truth_Info"]["RecoTrackPrimaryParticleTruePositionEnteringTMS"].array(library="np")
        self.RecoTrackPrimaryParticleTruePositionLeavingTMS = self.file["Truth_Info"]["RecoTrackPrimaryParticleTruePositionLeavingTMS"].array(library="np")
        self.RecoTrackPrimaryParticleTruePositionLeavingLAr = self.file["Truth_Info"]["RecoTrackPrimaryParticleTruePositionLeavingLAr"].array(library="np")
        self.RecoTrackPrimaryParticleVtxID = self.file["Truth_Info"]["RecoTrackPrimaryParticleVtxId"].array(library="np")

        self.RecoTrackSecondaryParticleIndex = self.file["Truth_Info"]["RecoTrackSecondaryParticleIndex"].array(library="np")
        self.RecoTrackSecondaryParticlePDG = self.file["Truth_Info"]["RecoTrackSecondaryParticlePDG"].array(library="np")
        self.RecoTrackSecondaryParticleTruePositionStart = self.file["Truth_Info"]["RecoTrackSecondaryParticleTruePositionStart"].array(library="np")
        self.RecoTrackSecondaryParticleTruePositionEnd = self.file["Truth_Info"]["RecoTrackSecondaryParticleTruePositionEnd"].array(library="np")
 
        self.TrueHitX = self.file["Truth_Info"]["TrueHitX"].array(library="np")
        self.TrueHitY = self.file["Truth_Info"]["TrueHitY"].array(library="np")
        self.TrueHitZ = self.file["Truth_Info"]["TrueHitZ"].array(library="np")
        self.TrueHitT = self.file["Truth_Info"]["TrueHitT"].array(library="np")
        self.TrueRecoHitX = self.file["Truth_Info"]["TrueRecoHitX"].array(library="np")
        self.TrueRecoHitY = self.file["Truth_Info"]["TrueRecoHitY"].array(library="np")
        self.TrueRecoHitZ = self.file["Truth_Info"]["TrueRecoHitZ"].array(library="np")
        self.TrueRecoHitT = self.file["Truth_Info"]["TrueRecoHitT"].array(library="np")

        self.TrueVtxN = self.file["Truth_Spill"]["TrueVtxN"].array(library="np")
        self.TrueVtxX = self.file["Truth_Spill"]["TrueVtxX"].array(library="np")
        self.TrueVtxY = self.file["Truth_Spill"]["TrueVtxY"].array(library="np")
        self.TrueVtxZ = self.file["Truth_Spill"]["TrueVtxZ"].array(library="np")
        self.TrueVtxT = self.file["Truth_Spill"]["TrueVtxT"].array(library="np")

        self.PDG = self.file["Truth_Spill"]["PDG"].array(library="np")
        self.TrueVtxPDG = self.file["Truth_Spill"]["TrueVtxPDG"].array(library="np")
        self.TrueVtxID = self.file["Truth_Spill"]["TrueVtxID"].array(library="np")
        self.VertexID = self.file["Truth_Spill"]["VertexID"].array(library="np")
        self.TrackID = self.file["Truth_Spill"]["TrackId"].array(library="np")
        self.TruthInfoIndex = self.file["Truth_Spill"]["TruthInfoIndex"].array(library="np")

        self.PositionLArStart = self.file["Truth_Spill"]["PositionLArStart"].array(library="np")
        self.PositionLArEnd = self.file["Truth_Spill"]["PositionLArEnd"].array(library="np")
        self.PositionTMSStart = self.file["Truth_Spill"]["PositionTMSStart"].array(library="np")
        self.PositionTMSEnd = self.file["Truth_Spill"]["PositionTMSEnd"].array(library="np")
        self.BirthPosition = self.file["Truth_Spill"]["BirthPosition"].array(library="np")
        self.DeathPosition = self.file["Truth_Spill"]["DeathPosition"].array(library="np")

        self.EventNo_TruthSpill = self.file["Truth_Spill"]["EventNo"].array(library="np")
        self.SpillNo_TruthSpill = self.file["Truth_Spill"]["SpillNo"].array(library="np")

        # Reco Tree
        self.RECO_StartPos = self.file["Reco_Tree"]["StartPos"].array(library="np")
        self.RECO_EndPos = self.file["Reco_Tree"]["EndPos"].array(library="np")

        # Line Candidates
        #self.Line_EventNo = self.file["Line_Candidates"]["EventNo"].array(library="np")
        #self.Line_SliceNo = self.file["Line_Candidates"]["SliceNo"].array(library="np")
        #self.Line_SpillNo = self.file["Line_Candidates"]["SpillNo"].array(library="np")
        #self.Line_RunNo = self.file["Line_Candidates"]["RunNo"].array(library="np")

## Setup driver to read ND-LAr info

In [7]:
## Call files and load SPINE driver to read spine file

cfg = f'''
base:
  verbosity: warning
build:
  mode: both
  fragments: false
  particles: true
  interactions: true
  units: cm
###  
post:
  match:
    particle:
      match_mode: both
    interaction:
      match_mode: both
###
io:
  reader:
    file_keys: {SPINE_file}
    skip_unknown_attrs: True
    name: hdf5
'''
driver = Driver(yaml.safe_load(cfg))

## Open TMS file and print tree / branch structure

In [8]:
file = uproot.open(TMS_file)

#  Set to track unique tree names
unique_trees = set()

print("Unique top-level trees and their branches:")

# Iterate through items in the ROOT file
for name, obj in file.items():
    # Check if the object is a TTree and if we haven't seen this tree name yet
    if isinstance(obj, uproot.TTree) and name not in unique_trees:
        print(f"\nTree: {name}")
        unique_trees.add(name)  # Add to set to avoid duplicates
        # List branches in the tree
        for branch in obj.keys():
            print(f"  Branch: {branch}")
file.close()

Unique top-level trees and their branches:

Tree: Line_Candidates;2
  Branch: EventNo
  Branch: SliceNo
  Branch: SpillNo
  Branch: RunNo
  Branch: nLinesU
  Branch: nLinesV
  Branch: nLinesX
  Branch: nLinesY
  Branch: nLines3D
  Branch: SlopeU
  Branch: InterceptU
  Branch: Slope_DownstreamU
  Branch: Intercept_DownstreamU
  Branch: Slope_UpstreamU
  Branch: Intercept_UpstreamU
  Branch: SlopeV
  Branch: InterceptV
  Branch: Slope_DownstreamV
  Branch: Intercept_DownstreamV
  Branch: Slope_UpstreamV
  Branch: Intercept_UpstreamV
  Branch: SlopeX
  Branch: InterceptX
  Branch: Slope_DownstreamX
  Branch: Intercept_DownstreamX
  Branch: Slope_UpstreamX
  Branch: Intercept_UpstreamX
  Branch: SlopeY
  Branch: InterceptY
  Branch: Slope_DownstreamY
  Branch: Intercept_DownstreamY
  Branch: Slope_UpstreamY
  Branch: Intercept_UpstreamY
  Branch: DirectionZU
  Branch: DirectionZV
  Branch: DirectionZX
  Branch: DirectionZY
  Branch: DirectionXU
  Branch: DirectionXV
  Branch: DirectionYX
  Branch: DirectionXY
  Branch: DirectionZU_Downstream
  Branch: DirectionXU_Downstream
  Branch: DirectionZU_Upstream
  Branch: DirectionXU_Upstream
  Branch: DirectionZV_Downstream
  Branch: DirectionXV_Downstream
  Branch: DirectionZV_Upstream
  Branch: DirectionXV_Upstream
  Branch: DirectionZX_Downstream
  Branch: DirectionYX_Downstream
  Branch: DirectionZX_Upstream
  Branch: DirectionZY_Upstream
  Branch: DirectionZY_Downstream
  Branch: DirectionXY_Downstream
  Branch: DirectionZY_Upstream
  Branch: DirectionXY_Upstream
  Branch: FirstHoughHitU
  Branch: FirstHoughHitV
  Branch: FirstHoughHitX
  Branch: FirstHoughHitY
  Branch: LastHoughHitU
  Branch: LastHoughHitV
  Branch: LastHoughHitX
  Branch: LastHoughHitY
  Branch: FirstHoughHitTimeU
  Branch: FirstHoughHitTimeV
  Branch: FirstHoughHitTimeX
  Branch: FirstHoughHitTimeY
  Branch: LastHoughHitTimeU
  Branch: LastHoughHitTimeV
  Branch: LastHoughHitTImeX
  Branch: LastHoughHitTImeY
  Branch: HoughEarliestHitTimeU
  Branch: HoughEarliestHitTimeV
  Branch: HoughEarliestHitTimeX
  Branch: HoughEarliestHitTimeY
  Branch: HoughLatestHitTimeU
  Branch: HoughLatestHitTimeV
  Branch: HoughLatestHitTimeX
  Branch: HoughLatestHitTimeY
  Branch: FirstHoughPlaneU
  Branch: FirstHoughPlaneV
  Branch: FirstHoughPlaneX
  Branch: FirstHoughPlaneY
  Branch: LastHoughPlaneU
  Branch: LastHoughPlaneV
  Branch: LastHoughPlaneX
  Branch: LastHoughPlaneY
  Branch: TMSStart
  Branch: TMSStartTime
  Branch: OccupancyU
  Branch: OccupancyV
  Branch: OccupancyX
  Branch: OccupancyY
  Branch: TrackLengthU
  Branch: TrackLengthV
  Branch: TrackLengthX
  Branch: TrackLengthY
  Branch: TotalTrackEnergyU
  Branch: TotalTrackEnergyV
  Branch: TotalTrackEnergyX
  Branch: TotalTrackEnergyY
  Branch: TrackStoppingU
  Branch: TrackStoppingV
  Branch: TrackStoppingX
  Branch: TrackStoppingY
  Branch: nHitsInTrackU
  Branch: nHitsInTrackV
  Branch: nHitsInTrackX
  Branch: nHitsInTrackY
  Branch: TrackHitEnergyU
  Branch: TrackHitEnergyV
  Branch: TrackHitEnergyX
  Branch: TrackHitEnergyY
  Branch: TrackHitPosU
  Branch: TrackHitPosV
  Branch: TrackHitPosX
  Branch: TrackHitPosY
  Branch: TrackHitTimeU
  Branch: TrackHitTimeV
  Branch: TrackHitTimeX
  Branch: TrackHitTimeY
  Branch: nClustersU
  Branch: nClustersV
  Branch: nClusterX
  Branch: nClusterY
  Branch: ClusterEnergyU
  Branch: ClusterEnergyV
  Branch: ClusterEnergyX
  Branch: ClusterEnergyY
  Branch: ClusterTimeU
  Branch: ClusterTimeV
  Branch: ClusterTimeX
  Branch: ClusterTimeY
  Branch: ClusterPosMeanU
  Branch: ClusterPosMeanV
  Branch: ClusterPosMeanX
  Branch: ClusterPosMeanY
  Branch: ClusterPosStdDevU
  Branch: ClusterPosStdDevV
  Branch: ClusterPosStdDevX
  Branch: ClusterPosStdDevY
  Branch: nHitsInClusterU
  Branch: nHitsInClusterV
  Branch: nHitsInClusterX
  Branch: nHitsInClusterY
  Branch: ClusterHitPosU
  Branch: ClusterHitPosV
  Branch: ClusterHitPosX
  Branch: ClusterHitPosY
  Branch: ClusterHitEnergyU
  Branch: ClusterHitEnergyV
  Branch: ClusterHitEnergyX
  Branch: ClusterHitEnergyY
  Branch: ClusterHitTimeU
  Branch: ClusterHitTimeV
  Branch: ClusterHitTimeX
  Branch: ClusterHitTimeY
  Branch: ClusterHitSliceU
  Branch: ClusterHitSliceV
  Branch: ClusterHitSliceX
  Branch: ClusterHitSliceY
  Branch: nHits
  Branch: RecoHitPos
  Branch: RecoHitEnergy
  Branch: RecoHitPE
  Branch: RecoHitBar
  Branch: RecoHitBarType
  Branch: RecoHitPlane
  Branch: RecoHitSlice

Tree: Line_Candidates;1
  Branch: EventNo
  Branch: SliceNo
  Branch: SpillNo
  Branch: RunNo
  Branch: nLinesU
  Branch: nLinesV
  Branch: nLinesX
  Branch: nLinesY
  Branch: nLines3D
  Branch: SlopeU
  Branch: InterceptU
  Branch: Slope_DownstreamU
  Branch: Intercept_DownstreamU
  Branch: Slope_UpstreamU
  Branch: Intercept_UpstreamU
  Branch: SlopeV
  Branch: InterceptV
  Branch: Slope_DownstreamV
  Branch: Intercept_DownstreamV
  Branch: Slope_UpstreamV
  Branch: Intercept_UpstreamV
  Branch: SlopeX
  Branch: InterceptX
  Branch: Slope_DownstreamX
  Branch: Intercept_DownstreamX
  Branch: Slope_UpstreamX
  Branch: Intercept_UpstreamX
  Branch: SlopeY
  Branch: InterceptY
  Branch: Slope_DownstreamY
  Branch: Intercept_DownstreamY
  Branch: Slope_UpstreamY
  Branch: Intercept_UpstreamY
  Branch: DirectionZU
  Branch: DirectionZV
  Branch: DirectionZX
  Branch: DirectionZY
  Branch: DirectionXU
  Branch: DirectionXV
  Branch: DirectionYX
  Branch: DirectionXY
  Branch: DirectionZU_Downstream
  Branch: DirectionXU_Downstream
  Branch: DirectionZU_Upstream
  Branch: DirectionXU_Upstream
  Branch: DirectionZV_Downstream
  Branch: DirectionXV_Downstream
  Branch: DirectionZV_Upstream
  Branch: DirectionXV_Upstream
  Branch: DirectionZX_Downstream
  Branch: DirectionYX_Downstream
  Branch: DirectionZX_Upstream
  Branch: DirectionZY_Upstream
  Branch: DirectionZY_Downstream
  Branch: DirectionXY_Downstream
  Branch: DirectionZY_Upstream
  Branch: DirectionXY_Upstream
  Branch: FirstHoughHitU
  Branch: FirstHoughHitV
  Branch: FirstHoughHitX
  Branch: FirstHoughHitY
  Branch: LastHoughHitU
  Branch: LastHoughHitV
  Branch: LastHoughHitX
  Branch: LastHoughHitY
  Branch: FirstHoughHitTimeU
  Branch: FirstHoughHitTimeV
  Branch: FirstHoughHitTimeX
  Branch: FirstHoughHitTimeY
  Branch: LastHoughHitTimeU
  Branch: LastHoughHitTimeV
  Branch: LastHoughHitTImeX
  Branch: LastHoughHitTImeY
  Branch: HoughEarliestHitTimeU
  Branch: HoughEarliestHitTimeV
  Branch: HoughEarliestHitTimeX
  Branch: HoughEarliestHitTimeY
  Branch: HoughLatestHitTimeU
  Branch: HoughLatestHitTimeV
  Branch: HoughLatestHitTimeX
  Branch: HoughLatestHitTimeY
  Branch: FirstHoughPlaneU
  Branch: FirstHoughPlaneV
  Branch: FirstHoughPlaneX
  Branch: FirstHoughPlaneY
  Branch: LastHoughPlaneU
  Branch: LastHoughPlaneV
  Branch: LastHoughPlaneX
  Branch: LastHoughPlaneY
  Branch: TMSStart
  Branch: TMSStartTime
  Branch: OccupancyU
  Branch: OccupancyV
  Branch: OccupancyX
  Branch: OccupancyY
  Branch: TrackLengthU
  Branch: TrackLengthV
  Branch: TrackLengthX
  Branch: TrackLengthY
  Branch: TotalTrackEnergyU
  Branch: TotalTrackEnergyV
  Branch: TotalTrackEnergyX
  Branch: TotalTrackEnergyY
  Branch: TrackStoppingU
  Branch: TrackStoppingV
  Branch: TrackStoppingX
  Branch: TrackStoppingY
  Branch: nHitsInTrackU
  Branch: nHitsInTrackV
  Branch: nHitsInTrackX
  Branch: nHitsInTrackY
  Branch: TrackHitEnergyU
  Branch: TrackHitEnergyV
  Branch: TrackHitEnergyX
  Branch: TrackHitEnergyY
  Branch: TrackHitPosU
  Branch: TrackHitPosV
  Branch: TrackHitPosX
  Branch: TrackHitPosY
  Branch: TrackHitTimeU
  Branch: TrackHitTimeV
  Branch: TrackHitTimeX
  Branch: TrackHitTimeY
  Branch: nClustersU
  Branch: nClustersV
  Branch: nClusterX
  Branch: nClusterY
  Branch: ClusterEnergyU
  Branch: ClusterEnergyV
  Branch: ClusterEnergyX
  Branch: ClusterEnergyY
  Branch: ClusterTimeU
  Branch: ClusterTimeV
  Branch: ClusterTimeX
  Branch: ClusterTimeY
  Branch: ClusterPosMeanU
  Branch: ClusterPosMeanV
  Branch: ClusterPosMeanX
  Branch: ClusterPosMeanY
  Branch: ClusterPosStdDevU
  Branch: ClusterPosStdDevV
  Branch: ClusterPosStdDevX
  Branch: ClusterPosStdDevY
  Branch: nHitsInClusterU
  Branch: nHitsInClusterV
  Branch: nHitsInClusterX
  Branch: nHitsInClusterY
  Branch: ClusterHitPosU
  Branch: ClusterHitPosV
  Branch: ClusterHitPosX
  Branch: ClusterHitPosY
  Branch: ClusterHitEnergyU
  Branch: ClusterHitEnergyV
  Branch: ClusterHitEnergyX
  Branch: ClusterHitEnergyY
  Branch: ClusterHitTimeU
  Branch: ClusterHitTimeV
  Branch: ClusterHitTimeX
  Branch: ClusterHitTimeY
  Branch: ClusterHitSliceU
  Branch: ClusterHitSliceV
  Branch: ClusterHitSliceX
  Branch: ClusterHitSliceY
  Branch: nHits
  Branch: RecoHitPos
  Branch: RecoHitEnergy
  Branch: RecoHitPE
  Branch: RecoHitBar
  Branch: RecoHitBarType
  Branch: RecoHitPlane
  Branch: RecoHitSlice

Tree: Reco_Tree;2
  Branch: EventNo
  Branch: SliceNo
  Branch: SpillNo
  Branch: RunNo
  Branch: nTracks
  Branch: nHits
  Branch: TrackHitPos
  Branch: nKalmanNodes
  Branch: KalmanPos
  Branch: KalmanPos_plus_chi2
  Branch: KalmanPos_minus_chi2
  Branch: RecoTrackKalmanFirstPlaneBarView
  Branch: RecoTrackKalmanLastPlaneBarView
  Branch: RecoTrackKalmanPlaneBarView
  Branch: KalmanTruePos
  Branch: RecoTrackKalmanFirstPlaneBarViewTrue
  Branch: RecoTrackKalmanLastPlaneBarViewTrue
  Branch: RecoTrackKalmanPlaneBarViewTrue
  Branch: StartDirection
  Branch: EndDirection
  Branch: StartPos
  Branch: EndPos
  Branch: EnergyRange
  Branch: EnergyDeposit
  Branch: Momentum
  Branch: Length
  Branch: Length_3D
  Branch: Charge
  Branch: Charge_Kalman
  Branch: Charge_Kalman_curvature
  Branch: Chi2_minus
  Branch: Chi2_plus
  Branch: TrackHitEnergies
  Branch: TrackHitBarType
  Branch: TimeSliceStartTime
  Branch: TimeSliceEndTime

Tree: Reco_Tree;1
  Branch: EventNo
  Branch: SliceNo
  Branch: SpillNo
  Branch: RunNo
  Branch: nTracks
  Branch: nHits
  Branch: TrackHitPos
  Branch: nKalmanNodes
  Branch: KalmanPos
  Branch: KalmanPos_plus_chi2
  Branch: KalmanPos_minus_chi2
  Branch: RecoTrackKalmanFirstPlaneBarView
  Branch: RecoTrackKalmanLastPlaneBarView
  Branch: RecoTrackKalmanPlaneBarView
  Branch: KalmanTruePos
  Branch: RecoTrackKalmanFirstPlaneBarViewTrue
  Branch: RecoTrackKalmanLastPlaneBarViewTrue
  Branch: RecoTrackKalmanPlaneBarViewTrue
  Branch: StartDirection
  Branch: EndDirection
  Branch: StartPos
  Branch: EndPos
  Branch: EnergyRange
  Branch: EnergyDeposit
  Branch: Momentum
  Branch: Length
  Branch: Length_3D
  Branch: Charge
  Branch: Charge_Kalman
  Branch: Charge_Kalman_curvature
  Branch: Chi2_minus
  Branch: Chi2_plus
  Branch: TrackHitEnergies
  Branch: TrackHitBarType
  Branch: TimeSliceStartTime
  Branch: TimeSliceEndTime

Tree: Truth_Info;2
  Branch: EventNo
  Branch: SpillNo
  Branch: RunNo
  Branch: IsCC
  Branch: Interaction
  Branch: TruthInfoIndex
  Branch: TruthInfoNSlices
  Branch: nPrimaryVertices
  Branch: HasPileup
  Branch: NeutrinoPDG
  Branch: NeutrinoP4
  Branch: NeutrinoX4
  Branch: nParticles
  Branch: LeptonPDG
  Branch: LeptonP4
  Branch: LeptonX4
  Branch: MuonP4
  Branch: Muon_Vertex
  Branch: Muon_Death
  Branch: Muon_TrueKE
  Branch: Muon_TrueTrackLength
  Branch: VertexIdOfMostEnergyInEvent
  Branch: VisibleEnergyFromVertexInSlice
  Branch: TotalVisibleEnergyFromVertex
  Branch: VisibleEnergyFromOtherVerticesInSlice
  Branch: VertexVisibleEnergyFractionInSlice
  Branch: PrimaryVertexVisibleEnergyFraction
  Branch: LArOuterShellEnergy
  Branch: LArTotalEnergy
  Branch: TotalNonTMSEnergy
  Branch: LArOuterShellEnergyFromVertex
  Branch: LArTotalEnergyFromVertex
  Branch: TotalNonTMSEnergyFromVertex
  Branch: RecoTrackN
  Branch: RecoTrackTrueVisibleEnergy
  Branch: RecoTrackPrimaryParticleIndex
  Branch: RecoTrackPrimaryParticleTrueVisibleEnergy
  Branch: RecoTrackPrimaryParticleTrueNHits
  Branch: RecoTrackSecondaryParticleIndex
  Branch: RecoTrackSecondaryParticleTrueVisibleEnergy
  Branch: RecoTrackSecondaryParticleTrueNHits
  Branch: RecoTrackPrimaryParticleTrueMomentumTrackStart
  Branch: RecoTrackPrimaryParticleTruePositionTrackStart
  Branch: RecoTrackPrimaryParticleTrueMomentumTrackEnd
  Branch: RecoTrackPrimaryParticleTruePositionTrackEnd
  Branch: RecoTrackNHits
  Branch: RecoTrackTrueHitPosition
  Branch: RecoTrackPrimaryParticleTrueTrackLengthAsMeasured
  Branch: RecoTrackPrimaryParticleTrueTrackLengthAsMeasuredIgnoreY
  Branch: RecoTrackPrimaryParticleTrueTrackLengthRecoStart
  Branch: RecoTrackPrimaryParticleTrueTrackLengthRecoStartIgnoreY
  Branch: RecoTrackPrimaryParticleTrueTrackLengthInTMSIgnoreY
  Branch: RecoTrackPrimaryParticlePDG
  Branch: RecoTrackPrimaryParticleIsPrimary
  Branch: RecoTrackPrimaryParticleTrueMomentum
  Branch: RecoTrackPrimaryParticleTruePositionStart
  Branch: RecoTrackPrimaryParticleTruePositionEnd
  Branch: RecoTrackPrimaryParticleTrueTrackLength
  Branch: RecoTrackPrimaryParticleTrueTrackLengthIgnoreY
  Branch: RecoTrackPrimaryParticleTrueTrackLengthInTMS
  Branch: RecoTrackPrimaryParticleTrueMomentumEnteringTMS
  Branch: RecoTrackPrimaryParticleTrueMomentumLeavingTMS
  Branch: RecoTrackPrimaryParticleTruePositionEnteringTMS
  Branch: RecoTrackPrimaryParticleTruePositionLeavingTMS
  Branch: RecoTrackPrimaryParticleTruePositionLeavingLAr
  Branch: RecoTrackPrimaryParticleTrueMomentumLeavingLAr
  Branch: RecoTrackPrimaryParticleTMSFiducialStart
  Branch: RecoTrackPrimaryParticleTMSFiducialTouch
  Branch: RecoTrackPrimaryParticleTMSFiducialEnd
  Branch: RecoTrackPrimaryParticleLArFiducialStart
  Branch: RecoTrackPrimaryParticleLArFiducialTouch
  Branch: RecoTrackPrimaryParticleLArFiducialEnd
  Branch: RecoTrackPrimaryParticleVtxId
  Branch: RecoTrackPrimaryParticleVtxFiducialCut
  Branch: RecoTrackPrimaryParticleVtxShellEnergyCut
  Branch: RecoTrackPrimaryParticleVtxNDPhysicsCut
  Branch: RecoTrackSecondaryParticlePDG
  Branch: RecoTrackSecondaryParticleIsPrimary
  Branch: RecoTrackSecondaryParticleTrueMomentum
  Branch: RecoTrackSecondaryParticleTruePositionStart
  Branch: RecoTrackSecondaryParticleTruePositionEnd
  Branch: NTrueHits
  Branch: TrueHitX
  Branch: TrueHitY
  Branch: TrueHitZ
  Branch: TrueHitT
  Branch: TrueHitE
  Branch: TrueHitPE
  Branch: TrueHitPEAfterFibers
  Branch: TrueHitPEAfterFibersLongPath
  Branch: TrueHitPEAfterFibersShortPath
  Branch: TrueNTrueParticles
  Branch: TrueLeptonicEnergy
  Branch: TrueHadronicEnergy
  Branch: TrueRecoHitX
  Branch: TrueRecoHitY
  Branch: TrueRecoHitZ
  Branch: TrueRecoHitTrackX
  Branch: TrueRecoHitTrackY
  Branch: TrueRecoHitTrackXUncertainty
  Branch: TrueRecoHitTrackYUncertainty
  Branch: TrueRecoHitNotZ
  Branch: TrueRecoHitT
  Branch: TrueRecoHitE
  Branch: TrueRecoHitPE
  Branch: TrueRecoHitEVis
  Branch: TrueRecoHitIsPedSupped
  Branch: TrueHitBar
  Branch: TrueHitPlane
  Branch: TrueHitView

Tree: Truth_Info;1
  Branch: EventNo
  Branch: SpillNo
  Branch: RunNo
  Branch: IsCC
  Branch: Interaction
  Branch: TruthInfoIndex
  Branch: TruthInfoNSlices
  Branch: nPrimaryVertices
  Branch: HasPileup
  Branch: NeutrinoPDG
  Branch: NeutrinoP4
  Branch: NeutrinoX4
  Branch: nParticles
  Branch: LeptonPDG
  Branch: LeptonP4
  Branch: LeptonX4
  Branch: MuonP4
  Branch: Muon_Vertex
  Branch: Muon_Death
  Branch: Muon_TrueKE
  Branch: Muon_TrueTrackLength
  Branch: VertexIdOfMostEnergyInEvent
  Branch: VisibleEnergyFromVertexInSlice
  Branch: TotalVisibleEnergyFromVertex
  Branch: VisibleEnergyFromOtherVerticesInSlice
  Branch: VertexVisibleEnergyFractionInSlice
  Branch: PrimaryVertexVisibleEnergyFraction
  Branch: LArOuterShellEnergy
  Branch: LArTotalEnergy
  Branch: TotalNonTMSEnergy
  Branch: LArOuterShellEnergyFromVertex
  Branch: LArTotalEnergyFromVertex
  Branch: TotalNonTMSEnergyFromVertex
  Branch: RecoTrackN
  Branch: RecoTrackTrueVisibleEnergy
  Branch: RecoTrackPrimaryParticleIndex
  Branch: RecoTrackPrimaryParticleTrueVisibleEnergy
  Branch: RecoTrackPrimaryParticleTrueNHits
  Branch: RecoTrackSecondaryParticleIndex
  Branch: RecoTrackSecondaryParticleTrueVisibleEnergy
  Branch: RecoTrackSecondaryParticleTrueNHits
  Branch: RecoTrackPrimaryParticleTrueMomentumTrackStart
  Branch: RecoTrackPrimaryParticleTruePositionTrackStart
  Branch: RecoTrackPrimaryParticleTrueMomentumTrackEnd
  Branch: RecoTrackPrimaryParticleTruePositionTrackEnd
  Branch: RecoTrackNHits
  Branch: RecoTrackTrueHitPosition
  Branch: RecoTrackPrimaryParticleTrueTrackLengthAsMeasured
  Branch: RecoTrackPrimaryParticleTrueTrackLengthAsMeasuredIgnoreY
  Branch: RecoTrackPrimaryParticleTrueTrackLengthRecoStart
  Branch: RecoTrackPrimaryParticleTrueTrackLengthRecoStartIgnoreY
  Branch: RecoTrackPrimaryParticleTrueTrackLengthInTMSIgnoreY
  Branch: RecoTrackPrimaryParticlePDG
  Branch: RecoTrackPrimaryParticleIsPrimary
  Branch: RecoTrackPrimaryParticleTrueMomentum
  Branch: RecoTrackPrimaryParticleTruePositionStart
  Branch: RecoTrackPrimaryParticleTruePositionEnd
  Branch: RecoTrackPrimaryParticleTrueTrackLength
  Branch: RecoTrackPrimaryParticleTrueTrackLengthIgnoreY
  Branch: RecoTrackPrimaryParticleTrueTrackLengthInTMS
  Branch: RecoTrackPrimaryParticleTrueMomentumEnteringTMS
  Branch: RecoTrackPrimaryParticleTrueMomentumLeavingTMS
  Branch: RecoTrackPrimaryParticleTruePositionEnteringTMS
  Branch: RecoTrackPrimaryParticleTruePositionLeavingTMS
  Branch: RecoTrackPrimaryParticleTruePositionLeavingLAr
  Branch: RecoTrackPrimaryParticleTrueMomentumLeavingLAr
  Branch: RecoTrackPrimaryParticleTMSFiducialStart
  Branch: RecoTrackPrimaryParticleTMSFiducialTouch
  Branch: RecoTrackPrimaryParticleTMSFiducialEnd
  Branch: RecoTrackPrimaryParticleLArFiducialStart
  Branch: RecoTrackPrimaryParticleLArFiducialTouch
  Branch: RecoTrackPrimaryParticleLArFiducialEnd
  Branch: RecoTrackPrimaryParticleVtxId
  Branch: RecoTrackPrimaryParticleVtxFiducialCut
  Branch: RecoTrackPrimaryParticleVtxShellEnergyCut
  Branch: RecoTrackPrimaryParticleVtxNDPhysicsCut
  Branch: RecoTrackSecondaryParticlePDG
  Branch: RecoTrackSecondaryParticleIsPrimary
  Branch: RecoTrackSecondaryParticleTrueMomentum
  Branch: RecoTrackSecondaryParticleTruePositionStart
  Branch: RecoTrackSecondaryParticleTruePositionEnd
  Branch: NTrueHits
  Branch: TrueHitX
  Branch: TrueHitY
  Branch: TrueHitZ
  Branch: TrueHitT
  Branch: TrueHitE
  Branch: TrueHitPE
  Branch: TrueHitPEAfterFibers
  Branch: TrueHitPEAfterFibersLongPath
  Branch: TrueHitPEAfterFibersShortPath
  Branch: TrueNTrueParticles
  Branch: TrueLeptonicEnergy
  Branch: TrueHadronicEnergy
  Branch: TrueRecoHitX
  Branch: TrueRecoHitY
  Branch: TrueRecoHitZ
  Branch: TrueRecoHitTrackX
  Branch: TrueRecoHitTrackY
  Branch: TrueRecoHitTrackXUncertainty
  Branch: TrueRecoHitTrackYUncertainty
  Branch: TrueRecoHitNotZ
  Branch: TrueRecoHitT
  Branch: TrueRecoHitE
  Branch: TrueRecoHitPE
  Branch: TrueRecoHitEVis
  Branch: TrueRecoHitIsPedSupped
  Branch: TrueHitBar
  Branch: TrueHitPlane
  Branch: TrueHitView

Tree: Truth_Spill;1
  Branch: EventNo
  Branch: SpillNo
  Branch: RunNo
  Branch: IsCC
  Branch: Interaction
  Branch: TruthInfoIndex
  Branch: TruthInfoNSlices
  Branch: nPrimaryVertices
  Branch: HasPileup
  Branch: NeutrinoPDG
  Branch: NeutrinoP4
  Branch: NeutrinoX4
  Branch: nTrueParticles
  Branch: nTruePrimaryParticles
  Branch: nTrueForgottenParticles
  Branch: VertexID
  Branch: Parent
  Branch: TrackId
  Branch: PDG
  Branch: IsPrimary
  Branch: TrueVisibleEnergy
  Branch: TrueNHits
  Branch: TruePathLength
  Branch: TruePathLengthIgnoreY
  Branch: TruePathLengthInTMS
  Branch: TruePathLengthInTMSIgnoreY
  Branch: InteractionTMSFiducial
  Branch: InteractionTMSFirstTwoModules
  Branch: InteractionTMSThin
  Branch: InteractionLArFiducial
  Branch: TMSFiducialStart
  Branch: TMSFiducialTouch
  Branch: TMSFiducialEnd
  Branch: LArFiducialStart
  Branch: LArFiducialTouch
  Branch: LArFiducialEnd
  Branch: BirthMomentum
  Branch: BirthPosition
  Branch: DeathMomentum
  Branch: DeathPosition
  Branch: MomentumLArStart
  Branch: PositionLArStart
  Branch: MomentumLArEnd
  Branch: PositionLArEnd
  Branch: MomentumTMSStart

## Inspect an ND-LAr spill

In [9]:
spill = 0    # For now only spill 0 works with vertex timing in TMS

data = driver.process(spill)
truth_particles = data[f'truth_particles']
print("Total nof true particles in ND-LAr spill", spill, "/", len(driver), ":", len(truth_particles))

NDLAr_pdg = np.array([p.pdg_code for p in truth_particles])
NDLAr_shape = np.array([p.shape for p in truth_particles])

NDLAr_ancestor_times = np.array([(p.ancestor_t - 1.2e9 * spill) for p in truth_particles])
rounded_NDLAr_ancestor_times = np.round(NDLAr_ancestor_times, 3)

NDLAr_start_times = np.array([(p.t - 1.2e9 * spill) for p in truth_particles])
NDLAr_end_times = np.array([(p.end_t - 1.2e9 * spill) for p in truth_particles])

NDLAr_start_x = np.array([p.position[0] for p in truth_particles])
NDLAr_end_x = np.array([p.end_position[0] for p in truth_particles])

NDLAr_start_y = np.array([p.position[1] for p in truth_particles])
NDLAr_end_y = np.array([p.end_position[1] for p in truth_particles])

NDLAr_start_z = np.array([p.position[2] for p in truth_particles])
NDLAr_end_z = np.array([p.end_position[2] for p in truth_particles])

NDLAr_ke = np.array([p.ke for p in truth_particles])
NDLAr_energy_init = np.array([p.energy_init for p in truth_particles])

NDLAr_truthpart = pd.DataFrame(
    {'PDG': NDLAr_pdg,
     'Shape': NDLAr_shape,
     'Ancestor Time': NDLAr_ancestor_times,
     'Start Time': NDLAr_start_times,
     'End Time': NDLAr_end_times,
     'Start Position X': NDLAr_start_x,
     'End Position X': NDLAr_end_x,
     'Start Position Y': NDLAr_start_y,
     'End Position Y': NDLAr_end_y,
     'Start Position Z': NDLAr_start_z,
     'End Position Z': NDLAr_end_z,
     'KE': NDLAr_ke,
     'Energy_init': NDLAr_energy_init
    })

pd.set_option('display.max_rows', None)
NDLAr_truthpart.head(50)

Total nof true particles in ND-LAr spill 0 / 13 : 770

,PDG,Shape,Ancestor Time,Start Time,End Time,Start Position X,End Position X,Start Position Y,End Position Y,Start Position Z,End Position Z,KE,Energy_init
0,13,1,76.406223,76.406223,230.167359,92.096222,-24.277039,316.716797,-566.628906,-1146.320068,3354.322021,16694.737092,16800.322266
1,11,3,76.406223,146.197139,146.288042,131.072845,132.259827,-89.582108,-89.531952,905.630432,907.025146,8.127530,8.638527
2,11,3,76.406223,145.798188,146.056475,130.839203,129.696289,-87.356232,-89.832764,893.882385,900.376831,46.412285,46.923439
3,11,3,76.406223,143.514508,143.675169,129.502380,128.913055,-74.530380,-75.096069,826.649963,830.597717,12.195357,12.706349
4,11,3,76.406223,142.248762,142.478013,128.788574,127.377777,-67.356506,-69.773590,789.397705,793.558594,16.099968,16.610924
5,11,3,76.406223,140.991196,141.156802,127.996490,126.342499,-60.202057,-59.781906,752.393005,756.330627,14.415388,14.926392
6,11,3,76.406223,139.990745,140.077995,127.317505,126.735046,-54.439819,-55.422394,722.968872,724.325867,6.484902,6.995896
7,11,3,76.406223,139.913936,139.998431,127.264740,127.671997,-53.996872,-53.903824,720.709961,722.685852,7.682404,8.193393
8,11,3,76.406223,136.623036,136.700832,125.133362,125.974457,-35.302887,-35.991989,623.868774,625.395813,5.447755,5.958759
9,11,3,76.406223,134.753315,134.833744,124.230042,124.603394,-24.728760,-26.103577,568.833374,569.120911,5.690864,6.201867
10,11,3,76.406223,133.573404,135.180605,123.653595,124.270752,-18.000778,-29.610260,534.113342,579.468811,324.135258,324.659668
11,13,1,190.502403,190.502403,213.503651,276.662720,-39.521973,-196.113892,26.686920,808.792358,1353.229980,1586.545056,1692.203979
12,2212,1,190.502403,190.502403,191.057416,276.662720,276.236389,-196.113892,-200.896332,808.792358,808.571777,76.119853,1014.391846
13,2212,1,190.502403,190.502403,190.946731,276.662720,278.171265,-196.113892,-195.608627,808.792358,805.611084,64.799139,1003.071167
14,2212,1,190.502403,190.502403,191.317759,276.662720,271.298096,-196.113892,-203.527237,808.792358,810.327271,115.724103,1053.996094
15,2212,1,190.502403,190.502403,191.380135,276.662720,277.411499,-196.113892,-190.636154,808.792358,816.542725,116.956365,1055.228394
16,2212,1,190.502403,190.502403,190.533933,276.662720,276.642273,-196.113892,-196.282639,808.792358,808.911438,24.519162,962.791199
17,11,0,190.502403,190.544227,190.565740,276.482544,276.557739,-196.065598,-195.662796,808.761047,808.739624,1.821392,2.332391
18,22,0,190.502403,190.502403,191.799248,276.662720,294.383545,-196.113876,-163.783142,808.792358,821.130371,302.577648,302.681885
19,11,0,190.502403,191.677611,192.465744,304.091614,319.317017,-189.991623,-184.872528,830.039795,844.144592,94.775822,95.287796
20,11,0,190.502403,196.194989,196.262666,230.280151,230.737366,-201.300140,-200.690216,841.639893,841.080444,5.633402,6.144396
21,2212,1,190.502403,195.679846,195.750239,223.074463,223.185425,-197.305740,-197.565796,854.702393,854.780273,15.585063,953.857056
22,2212,1,190.502403,191.317759,191.443557,271.298096,270.726196,-203.527237,-203.391113,810.327271,810.573486,24.151762,962.423767
23,11,3,190.502403,191.171864,191.257120,268.610352,266.871033,-189.568909,-189.096802,825.923767,827.216187,5.953485,6.464481
24,13,1,285.991180,285.991180,372.636819,-520.175720,-310.887909,230.578583,-167.181915,-1762.537231,764.701965,11635.089286,11740.754883
25,13,1,437.869526,437.869526,519.411125,-281.528931,-340.142700,-20.481125,-696.029968,-319.234467,1992.963135,3842.199001,3947.852539
26,13,1,494.506181,494.506181,555.105421,-102.420471,-658.818726,82.577454,-281.836060,636.136780,2310.815918,3624.602834,3730.262451
27,2212,1,494.506181,494.711268,494.954134,-100.619751,-99.083923,81.219696,81.020996,637.989502,637.528076,46.721203,984.993225
28,11,0,494.506181,506.120534,506.191598,-38.747833,-39.738312,-50.681366,-49.994354,800.665527,799.461609,5.128077,5.639077
29,2212,1,494.506181,504.559465,504.645281,-34.037659,-34.360016,-75.298889,-75.508835,792.284912,792.312439,18.357472,956.629517
30,2212,1,494.506181,503.567535,509.134436,-37.504028,-6.794464,-63.738113,-102.588486,798.104492,903.266602,563.598808,1501.870850
31,2212,1,494.506181,509.134436,509.169319,-6.794464,-6.844849,-102.588486,-102.614639,903.266602,903.165771,9.298084,947.570068
32,2212,1,494.506181,509.134436,510.339384,-6.794464,-6.413361,-102.588486,-113.392525,903.266602,911.397034,138.044536,1076.316528
33,2212,1,494.506181,494.618898,496.887690,-101.302307,-81.271423,82.339417,74.033936,639.074036,698.341309,1647.786855,2586.058838
34,22,0,494.506181,496.887690,497.545220,-81.271423,-65.066650,74.033936,73.469147,698.341309,709.551086,49.818478,49.818478
35,22,0,494.506181,496.887690,497.545753,-81.271423,-92.977753,74.033936,77.821350,698.341309,682.919861,94.358711,94.358711
36,2212,1,494.506181,496.887690,497.161722,-81.271423,-82.363586,74.033936,75.531006,698.341309,698.379761,44.461454,982.733459
37,211,1,494.506181,496.887690,512.850339,-81.271423,-69.131042,74.033936,85.720398,698.341309,698.599304,75.011391,214.581497
38,2212,1,494.506181,496.887690,497.686318,-81.271423,-76.195862,74.033936,71.882263,698.341309,703.906250,99.763501,1038.035522
39,2212,1,494.506181,498.555075,498.948370,-102.749603,-105.389221,71.606750,70.320099,702.881958,702.194519,58.071755,996.343750
40,2212,1,494.506181,496.887690,497.540160,-81.271423,-76.428162,74.033936,68.883179,698.341309,709.023132,312.751447,1251.023438
41,2212,1,494.506181,497.540160,497.655905,-76.428162,-76.252075,68.883179,68.508942,709.023132,709.415039,22.953462,961.225464
42,2212,1,494.506181,497.540160,499.494459,-76.428162,-74.456604,68.883179,64.996521,709.023132,734.330383,205.557744,1143.829712
43,2212,1,494.506181,496.887690,497.786719,-81.271423,-84.843811,74.033936,73.233948,698.341309,716.185242,359.898594,1298.170532
44,2212,1,494.506181,497.786719,498.807233,-84.843811,-86.808075,73.233948,78.323975,716.185242,732.418335,230.308733,1168.580688
45,2212,1,494.506181,498.807233,500.002445,-86.808075,-87.212708,78.323975,82.779877,732.418335,745.017456,136.260885,1074.532837
46,11,3,494.506181,504.062944,504.341752,-212.646255,-215.242157,20.291245,19.643250,892.959473,899.845825,18.288401,18.799429
47,11,3,494.506181,503.335413,503.486256,-204.526825,-206.620483,24.629303,23.404877,873.200928,876.291504,16.848247,17.359243
48,11,3,494.506181,500.447288,500.543439,-171.400146,-173.382721,42.857391,42.781342,795.364807,795.896301,6.889570,7.400569
49,11,3,494.506181,498.897453,499.094804,-153.589676,-153.244385,52.870605,51.486176,753.661804,757.887634,25.922680,26.433737

In [10]:
truth_interactions = data[f'truth_interactions']
print("Total nof true interactions in ND-LAr spill", spill, "/", len(driver), ":", len(truth_interactions))

itx = 0
print(f"\nTake a quick look at interaction {itx} / {len(truth_interactions)}:")
print("ID:", truth_interactions[itx].id)
print("Vertex:", truth_interactions[itx].vertex)
print("Vertex Time:", truth_interactions[itx].t)
print("Particle IDs:", truth_interactions[itx].particle_ids)
print("Primary Particle IDs:", truth_interactions[itx].primary_particle_ids)
print("Interaction ID", truth_interactions[itx].interaction_id)
print("Track ID", truth_interactions[itx].track_id)
print("Position:", truth_interactions[itx].position)

NDLAr_vtx_x = np.array([p.vertex[0] for p in truth_interactions])
NDLAr_vtx_y = np.array([p.vertex[1] for p in truth_interactions])
NDLAr_vtx_z = np.array([p.vertex[2] for p in truth_interactions])

NDLAr_interaction_id = np.array([p.interaction_id for p in truth_interactions])
NDLAr_track_id = np.array([p.track_id for p in truth_interactions])
NDLAr_t = np.array([(p.t - 1.2e9 * spill) for p in truth_interactions])

NDLAr_position_x = np.array([p.position[0] for p in truth_interactions])  # Seems to be the same as the 'vertex' variable
NDLAr_position_y = np.array([p.position[1] for p in truth_interactions])
NDLAr_position_z = np.array([p.position[2] for p in truth_interactions])

NDLAr_truthinteraction = pd.DataFrame(
    {'t': NDLAr_t,
     'Vtx x': NDLAr_vtx_x,
     'Vtx y': NDLAr_vtx_y,
     'Vtx z': NDLAr_vtx_z,
     'Interaction id': NDLAr_interaction_id,
     'Track id': NDLAr_track_id
    })

pd.set_option('display.max_rows', None)
NDLAr_truthinteraction.head(85) # 0 - 85

Total nof true interactions in ND-LAr spill 0 / 13 : 86

Take a quick look at interaction 0 / 86:
ID: 0
Vertex: [ 276.66272 -196.11389  808.79236]
Vertex Time: 190.502403
Particle IDs: [11 12 13 14 15 16 17 18 19 20 21 22 23]
Primary Particle IDs: [11 12 13 14 15 16 18]
Interaction ID 24710000000
Track ID 4294967295
Position: [ 276.66272 -196.11389  808.79236]

,t,Vtx x,Vtx y,Vtx z,Interaction id,Track id
0,190.502403,276.662720,-196.113892,808.792358,24710000000,4294967295
1,494.506181,-102.420471,82.577454,636.136780,24710000001,4294967295
2,684.474673,219.380493,108.004028,493.899048,24710000002,4294967295
3,855.082319,-62.927734,-213.308273,473.906158,24710000003,4294967295
4,969.567374,-118.417938,-23.385559,623.098328,24710000004,4294967295
5,1851.062917,8.840057,56.511505,589.128113,24710000006,4294967295
6,2003.030335,191.141846,16.478455,558.594604,24710000007,4294967295
7,2136.083174,-204.364029,18.369858,898.149475,24710000008,4294967295
8,2421.392313,36.647949,-86.342941,512.630920,24710000009,4294967295
9,2953.519672,56.644989,-170.136993,897.176270,24710000011,4294967295
10,3493.338728,-118.051636,-99.205811,623.705139,24710000013,4294967295
11,3569.400392,327.384399,64.151611,636.262512,24710000014,4294967295
12,3607.460106,-92.956268,-18.558075,676.144592,24710000015,4294967295
13,3664.943716,340.630981,-161.007126,677.659180,24710000016,4294967295
14,4253.182284,142.424194,96.738037,538.989075,24710000017,4294967295
15,4595.624610,39.619690,64.944305,826.903015,24710000019,4294967295
16,6104.698196,-0.903229,-146.187622,587.475098,24710000020,4294967295
17,6180.637131,-89.180786,-116.086006,823.577148,24710000021,4294967295
18,6465.665563,11.107300,-65.395462,477.278870,24710000022,4294967295
19,6872.699267,59.504791,-149.169342,785.868652,24710000023,4294967295
20,6986.440820,339.554810,109.167297,587.204468,24710000024,4294967295
21,7917.658636,215.559937,-33.720947,432.117218,24710000025,4294967295
22,8989.830812,112.274811,-26.592117,476.504028,24710000026,4294967295
23,9578.540043,-278.955811,-103.185074,744.194519,24710000027,4294967295
24,4177.109583,251.535400,172.221802,-557.310913,1000008710000432,4294967295
25,7632.953039,-384.946503,570.730469,34.389099,1000008710001446,4294967295
26,836.616748,-53.890472,116.482147,-277.569000,1000008710001916,4294967295
27,4861.708326,-147.893906,79.644409,-543.476929,1000008710002257,4294967295
28,1965.735084,-157.742554,-5.359238,-735.887329,1000008710002331,4294967295
29,6522.745070,-280.491852,78.980469,406.368042,1000008710003235,4294967295
30,5078.767354,57.209167,217.351501,385.354980,1000008710003590,4294967295
31,285.991180,-520.175720,230.578583,-1762.537231,1000008710003655,4294967295
32,1216.233917,-17.121887,-196.174225,-826.539917,1000008711000766,4294967295
33,3219.966159,-68.554596,203.336182,-2224.179932,1000008711003518,4294967295
34,9597.070310,160.698914,129.625305,-303.389252,1000008711003605,4294967295
35,7537.354404,-308.589355,-230.393616,433.366394,1000008712000328,4294967295
36,8088.034699,-247.509811,151.068298,-297.428497,1000008712000970,4294967295
37,3740.300273,-352.894012,-5.591873,534.395081,1000008712001250,4294967295
38,6579.186749,-258.683716,-30.162064,-227.630829,1000008712001558,4294967295
39,5800.897268,-51.814056,218.754974,-3896.774902,1000008712001604,4294967295
40,437.869526,-281.528931,-20.481125,-319.234467,1000008712001748,4294967295
41,3474.222621,-83.170776,-268.734558,-75.689240,1000008712001749,4294967295
42,5097.677710,243.914185,-5.109787,-903.484985,1000008712002730,4294967295
43,779.915060,247.508423,367.855896,-232.122528,1000008712002813,4294967295
44,2953.235174,-234.035675,11.040833,-76.759186,1000008712003187,4294967295
45,5553.396742,54.450684,-433.524475,-265.830780,1000008713002003,4294967295
46,4329.254470,-256.232422,205.554718,-1872.823608,1000008713002401,4294967295
47,3379.108545,224.222534,-1.556091,-277.817047,1000008713002934,4294967295
48,7917.703097,7.298737,291.857910,-42.393433,1000008713003225,4294967295
49,608.827913,-85.637848,56.064484,-845.545654,1000008713003452,4294967295
50,6161.644289,-239.512375,67.025452,-1130.381348,1000008714000120,4294967295
51,4937.785004,-130.828339,49.912994,-252.408478,1000008714000731,4294967295
52,5078.059081,-232.200195,281.679993,-1078.057983,1000008714000910,4294967295
53,4690.826200,-48.991150,386.128479,-2414.988037,1000008714001327,4294967295
54,6199.863635,-16.345306,598.675232,-2714.131348,1000008714002360,4294967295
55,1851.749018,-351.587982,-4.263443,756.519287,1000008714003123,4294967295
56,1292.125539,49.658051,294.736023,-807.558472,1000008714003685,4294967295
57,9882.073660,-77.218323,15.490326,-557.223999,1000008715000503,4294967295
58,665.226978,207.091736,-223.263992,-1795.632446,1000008715002955,4294967295
59,6123.191001,274.518677,-462.298523,-54.231842,1000008715003549,4294967295
60,76.406223,92.096222,316.716797,-1146.320068,1000008716000007,4294967295
61,1349.140655,-271.384521,-278.673096,629.227112,1000008716000587,4294967295
62,6104.554332,56.546875,463.934875,-1179.624146,1000008716000627,4294967295
63,9141.493614,-162.347794,172.751160,-1753.217407,1000008716001237,4294967295
64,7252.599615,190.071106,-276.669800,-109.591156,1000008716001856,4294967295
65,9540.961667,-305.536041,-136.023407,-649.152222,1000008716002373,4294967295
66,1235.837354,-77.633606,-303.113892,462.673676,1000008716002722,4294967295
67,5762.305228,-265.474976,470.338928,-5406.517578,1000008717000785,4294967295
68,7746.499128,112.013428,78.749664,-1172.243896,1000008717001214,4294967295
69,5610.078862,327.568115,489.879089,-2523.704102,1000008717001665,4294967295
70,7366.636585,-556.024170,-124.931328,-106.806366,1000008717001890,4294967295
71,8164.658958,-155.733429,-286.718536,-24.728180,1000008717002532,4294967295
72,6218.567923,41.990540,70.405670,-1361.127075,1000008717003080,4294967295
73,8419.318018,-204.345276,172.992249,-1357.255615,1000008717003401,4294967295
74,3029.832380,-92.369873,168.890869,-37.364471,1000008718000111,4294967295
75,7746.309219,-57.025360,75.601807,-1358.869751,1000008718000202,4294967295
76,4424.847126,451.493774,-77.741821,-448.102753,1000008718000239,4294967295
77,6066.432626,-340.263458,-344.723663,180.556625,1000008718000551,4294967295
78,9293.844468,28.360596,155.240875,-173.304047,1000008718001029,4294967295
79,6853.852637,68.784058,46.031372,-377.035065,1000008718001031,4294967295
80,931.563941,91.231506,-245.009491,-67.177917,1000008718002997,4294967295
81,9502.557210,-284.926575,-90.856140,-77.026031,1000008719000168,4294967295
82,2820.744353,-231.876251,295.165222,-439.581879,1000008719000477,4294967295
83,4177.844209,234.046265,186.232849,-32.953003,1000008719001628,4294967295
84,6815.175579,429.071838,-120.392189,951.187256,1000008719001729,4294967295

In [11]:
# 1. Group the particle indices by their Start Time
# This creates a Series where the index is 'Time' and the value is a list of row indices
time_to_particle_indices = NDLAr_truthpart.groupby('Ancestor Time').indices

# 2. Map these indices back to the truth interaction dataframe
NDLAr_truthinteraction['particle_indices'] = NDLAr_truthinteraction['t'].map(time_to_particle_indices)

## Open TMS File and look at it

In [12]:
TMS = TMSData(TMS_file)
print("Total Entries:", len(TMS.EventNo))
print("Looking at spill", spill, "/", TMS.SpillNo[-1])
print()

# Create a 'mask' of True/False values to look at a single spill
mask = (TMS.SpillNo == spill)

# Get only the indices in chosen spill (where the mask is True)
TMS_indices = np.where(mask)[0]
print("All TMS indices in spill", spill, ":")
print(TMS_indices)

print()

print("Truth Info Index:", TMS.TruthInfoIndex)  # This just gives the first index of the spill

Total Entries: 1234
Looking at spill 0 / 12

All TMS indices in spill 0 :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92]

Truth Info Index: [   0   93  182  280  373  473  566  663  753  849  929 1041 1135]

In [13]:
print("\033[1;4;91mTMS info dump\033[0m")

x_nodes, y_nodes, z_nodes = [], [], []

# Create lists to hold the segmented line data
x_lines_reco, y_lines_reco, z_lines_reco = [], [], []

# Create lists to hold the segmented line data
x_lines_recotrue, y_lines_recotrue, z_lines_recotrue = [], [], []

matched_indices = []
matched_tracks = []
matched_x_nodes, matched_y_nodes, matched_z_nodes = [], [], []
matched_track_start, matched_track_end = [], []

sel_PositionLArStart = []
sel_PositionLArEnd = []
sel_PositionTMSStart = []
sel_PositionTMSEnd = []

print("Truth Spill Times:")
formatted_times = [f"{x:.10f}" for x in TMS.TrueVtxT[spill]]
print(formatted_times[0:50])

truth_info_times = []

print()
print("Truth Info Times")

for i in TMS_indices:  # This gets everything from the current spill from the Truth_Info tree
   truth_info_times.append(float(TMS.NeutrinoX4[i][3]))

print(truth_info_times)

# Now loop over the relevant hits
#for i in TMS_indices:
for i, info_idx in enumerate(TMS_indices, start=0):
    print("\nEntry index", info_idx, "/", max(TMS_indices))
    print("Event", TMS.EventNo[info_idx], "/", max(TMS.EventNo))
    # print("Run No:", TMS.RunNo[i])

    print("Muon Vertex", TMS.MuonVertex[i])
    
    # Store every hit in TMS for this event
    x_nodes.extend(TMS.TrueHitX[i])
    y_nodes.extend(TMS.TrueHitY[i])
    z_nodes.extend(TMS.TrueHitZ[i])

    # Get basic info
    # vertexID = TMS.VertexID[i]
    # trackID = TMS.TrackID[i]
    # PDG = TMS.PDG[i]
   
    # print("TruthInfoIndex:", TruthInfoIndex)
    # print("VertexID:", vertexID)
    # print("TrackID:", trackID)
    # print("PDG:", PDG)

    # Primary Particle info
    RecoTrackPrimaryParticleVtxID = TMS.RecoTrackPrimaryParticleVtxID[i]
    RecoTrackPrimaryParticlePDG = TMS.RecoTrackPrimaryParticlePDG[i]
    RecoTrackPrimaryParticleIndex = TMS.RecoTrackPrimaryParticleIndex[i]

    print("RecoTrackPrimaryParticleVtxID:", RecoTrackPrimaryParticleVtxID)
    print("RecoTrackPrimaryParticlePDG:", RecoTrackPrimaryParticlePDG)    
    print("RecoTrackPrimaryParticleIndex:", RecoTrackPrimaryParticleIndex)

    RecoTrackPrimaryParticleTruePositionEnteringTMS = TMS.RecoTrackPrimaryParticleTruePositionEnteringTMS[i]
    RecoTrackPrimaryParticleTruePositionLeavingTMS = TMS.RecoTrackPrimaryParticleTruePositionLeavingTMS[i]
    RecoTrackPrimaryParticleTruePositionLeavingLAr = TMS.RecoTrackPrimaryParticleTruePositionLeavingLAr[i]

    #Secondary Particle info
    RecoTrackSecondaryParticleIndex = TMS.RecoTrackSecondaryParticleIndex[i]
    RecoTrackSecondaryParticlePDG = TMS.RecoTrackSecondaryParticlePDG[i]
    

    #PositionLArStart.extend(TMS.PositionLArStart[i])
    #PositionLArEnd.extend(TMS.PositionLArEnd[i])
    #PositionTMSStart.extend(TMS.PositionTMSStart[i])
    #PositionTMSEnd.extend(TMS.PositionTMSEnd[i])
    
    # Get track start and end points
    RECO_StartPos = TMS.RECO_StartPos[i]
    RECO_EndPos = TMS.RECO_EndPos[i]

    RECOTRUE_StartPos = TMS.RecoTrackPrimaryParticleTruePositionTrackStart[i]
    RECOTRUE_EndPos = TMS.RecoTrackPrimaryParticleTruePositionTrackEnd[i]

    #BirthPosition = TMS.BirthPosition[i]
    #print("Birth Position:", BirthPosition)
    
    print("RecoTrackPrimaryParticleTruePositionLeavingLAr:", RecoTrackPrimaryParticleTruePositionLeavingLAr)
    print("RecoTrackPrimaryParticleTruePositionEnteringTMS:", RecoTrackPrimaryParticleTruePositionEnteringTMS)
    print("RecoTrackPrimaryParticleTruePositionLeavingTMS:", RecoTrackPrimaryParticleTruePositionLeavingTMS)

    print("RecoTrackSecondaryParticlePDG:", RecoTrackSecondaryParticlePDG)
    print("RecoTrackSecondaryParticleIndex:", RecoTrackSecondaryParticleIndex)

    TrueVtxT = TMS.TrueVtxT[spill][i]
    TrueVtxX = TMS.TrueVtxX[spill][i]
    TrueVtxY = TMS.TrueVtxY[spill][i]
    TrueVtxZ = TMS.TrueVtxZ[spill][i]
    print("\033[91mTrue Vertex Time:", TrueVtxT, "\033[0m")
    print("TrueVtxX:", TrueVtxX)
    print("TrueVtxY:", TrueVtxY)
    print("TrueVtxZ:", TrueVtxZ)

    # Check for matches between TMS tracks and ND-Lar tracks
    mask = np.isclose(rounded_NDLAr_ancestor_times, TrueVtxT, atol=1e-3)

    if np.any(mask):
        matched_tracks.append([i, np.where(mask)[0], TrueVtxT])
    
    if np.any(np.isclose(rounded_NDLAr_ancestor_times, TrueVtxT, atol=1e-3)):
        print("\033[91m")
        print("MATCH")
        matched_indices.append(info_idx)
        start_coord = RECOTRUE_StartPos.flatten()
        end_coord = RECOTRUE_EndPos.flatten()
        print("RECO_StartPos: ", TMS.RECO_StartPos[i])
        print("RECO_EndPos: ", TMS.RECO_EndPos[i])
        print()
        print("RECOTRUE_StartPos:", start_coord)
        print("RECOTRUE_EndPos:", end_coord)
        
        if RECOTRUE_StartPos.size > 0:
            matched_x_nodes.extend([start_coord[0], end_coord[0], None])    # The 'None' lifts the plotly pen
            matched_y_nodes.extend([start_coord[1], end_coord[1], None])
            matched_z_nodes.extend([start_coord[2], end_coord[2], None])
            matched_track_start.append([start_coord[0], start_coord[1], start_coord[2]])
            matched_track_end.append([end_coord[0], end_coord[1], end_coord[2]])
        else:
            print("No reco track associated with this match")
        
        print("\033[0m")
            
    for start, end in zip(RECO_StartPos, RECO_EndPos):
        x_lines_reco.extend([start[0], end[0], None])
        y_lines_reco.extend([start[1], end[1], None])
        z_lines_reco.extend([start[2], end[2], None])

    for start, end in zip(RECOTRUE_StartPos, RECOTRUE_EndPos):
        x_lines_recotrue.extend([start[0], end[0], None])
        y_lines_recotrue.extend([start[1], end[1], None])
        z_lines_recotrue.extend([start[2], end[2], None])

TMS info dump
Truth Spill Times:
['0.7299720049', '19.2659912109', '76.4062271118', '95.9215240479', '152.0167236328', '171.7185211182', '190.5023956299', '190.9931030273', '285.9911804199', '304.3083801270', '361.8605957031', '380.6953735352', '399.3994445801', '399.7138671875', '399.7648620605', '437.8695373535', '456.0197753906', '456.3215026855', '475.6371154785', '494.1216430664', '494.4869079590', '494.5061950684', '513.9501953125', '532.9518432617', '608.8279418945', '627.1353759766', '627.5316162109', '646.9359741211', '665.2269897461', '684.4746704102', '684.5284423828', '684.7940063477', '703.2173461914', '703.6740722656', '722.6079101562', '741.1098022461', '760.3746337891', '760.5453491211', '760.8781127930', '779.3172607422', '779.9150390625', '817.4758300781', '836.6167602539', '836.8333740234', '855.0823364258', '874.0092773438', '893.0070190430', '912.2619018555', '931.5639648438', '969.5673828125']

Truth Info Times
[0.7299720048904419, 76.4062271118164, 304.3083801269531, 494.4869079589844, 741.1098022460938, 779.3172607421875, 836.6167602539062, 988.314453125, 1026.1341552734375, 1216.87255859375, 1216.23388671875, 1292.12548828125, 1406.4459228515625, 1577.6572265625, 1965.1422119140625, 1965.735107421875, 2212.653564453125, 2288.454833984375, 2288.454833984375, 2364.29248046875, 2516.293701171875, 2592.85107421875, 2915.667724609375, 2953.519775390625, 3200.42333984375, 3238.10986328125, 3360.003662109375, 3474.780029296875, 3531.575439453125, 3569.439453125, 3607.460205078125, 3740.30029296875, 3835.668701171875, 3797.806640625, 4006.277099609375, 4234.3173828125, 4234.69091796875, 4253.50244140625, 4405.5458984375, 4424.84716796875, 4538.69482421875, 4595.62451171875, 4671.94580078125, 4690.826171875, 4899.8681640625, 4937.78515625, 5078.767578125, 5097.677734375, 5230.45263671875, 5382.6865234375, 5439.55029296875, 5458.3818359375, 5572.35009765625, 5610.0791015625, 5819.67333984375, 5800.8974609375, 6123.9541015625, 6180.63720703125, 6161.64453125, 6218.56787109375, 6579.4970703125, 6777.49267578125, 6853.0205078125, 7005.091796875, 7100.66796875, 7195.82958984375, 7252.69921875, 7347.2392578125, 7442.98974609375, 7442.98974609375, 7423.39599609375, 7632.52783203125, 7689.10009765625, 7689.10009765625, 7784.396484375, 7746.30908203125, 7879.2412109375, 7955.19287109375, 8069.81884765625, 8088.03466796875, 8221.923828125, 8419.318359375, 8590.6298828125, 8799.19140625, 9027.8544921875, 9160.0947265625, 9141.4931640625, 9540.9619140625, 9749.7529296875, 9806.8720703125, 9863.056640625, 9711.4462890625, 9882.0732421875]

Entry index 0 / 92
Event 0 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 0.729972
TrueVtxX: -3662.2812
TrueVtxY: 4246.9546
TrueVtxZ: 22541.07

Entry index 1 / 92
Event 436 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: [2]
RecoTrackPrimaryParticlePDG: [13]
RecoTrackPrimaryParticleIndex: [3565]
RecoTrackPrimaryParticleTruePositionLeavingLAr: [[1286.8541  -664.4281  7846.705    142.08812]]
RecoTrackPrimaryParticleTruePositionEnteringTMS: [[ 1347.0327 -1303.7041 11169.5      153.3777]]
RecoTrackPrimaryParticleTruePositionLeavingTMS: [[ 1101.8909  -2579.841   18494.5       178.22092]]
RecoTrackSecondaryParticlePDG: [-1000000000]
RecoTrackSecondaryParticleIndex: [-999999999]
True Vertex Time: 19.265991
TrueVtxX: 3640.1191
TrueVtxY: -566.30963
TrueVtxZ: 16235.093

Entry index 2 / 92
Event 437 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 76.40623
TrueVtxX: 920.96185
TrueVtxY: 3167.168
TrueVtxZ: -11463.2

MATCH
RECO_StartPos:  []
RECO_EndPos:  []

RECOTRUE_StartPos: []
RECOTRUE_EndPos: []
No reco track associated with this match


Entry index 3 / 92
Event 438 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: [18 20]
RecoTrackPrimaryParticlePDG: [  13 -211]
RecoTrackPrimaryParticleIndex: [3378 3368]
RecoTrackPrimaryParticleTruePositionLeavingLAr: [[-1.e+08 -1.e+08 -1.e+08 -1.e+08]
 [-1.e+08 -1.e+08 -1.e+08 -1.e+08]]
RecoTrackPrimaryParticleTruePositionEnteringTMS: [[ 1096.8055    268.84296 14104.5       479.4236 ]
 [-1124.1389  -2719.257   12922.186     496.4509 ]]
RecoTrackPrimaryParticleTruePositionLeavingTMS: [[  810.6599  -1483.8127  18179.562     494.60757]
 [-1093.3466  -2734.6997  13231.009     497.57922]]
RecoTrackSecondaryParticlePDG: [  13 2212]
RecoTrackSecondaryParticleIndex: [3337 3369]
True Vertex Time: 95.921524
TrueVtxX: 3261.4937
TrueVtxY: 3553.9312
TrueVtxZ: -29938.87

Entry index 4 / 92
Event 439 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 152.01672
TrueVtxX: 2070.8906
TrueVtxY: -2862.7026
TrueVtxZ: 22430.78

Entry index 5 / 92
Event 440 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: [36 39 39 28]
RecoTrackPrimaryParticlePDG: [ 13  13 211 -13]
RecoTrackPrimaryParticleIndex: [3212 3192 3193 3272]
RecoTrackPrimaryParticleTruePositionLeavingLAr: [[-1.0000000e+08 -1.0000000e+08 -1.0000000e+08 -1.0000000e+08]
 [-1.0000000e+08 -1.0000000e+08 -1.0000000e+08 -1.0000000e+08]
 [-1.0000000e+08 -1.0000000e+08 -1.0000000e+08 -1.0000000e+08]
 [ 2.2727085e+03 -1.4614719e+03  8.9957549e+03  7.5542755e+02]]
RecoTrackPrimaryParticleTruePositionEnteringTMS: [[  629.35944 -2000.8855  11798.347     760.37463]
 [ 2661.0354   -580.2011  11733.956     779.31726]
 [ 2661.0354   -580.2011  11733.956     779.31726]
 [ 1982.6249  -1069.235   11217.972     763.24194]]
RecoTrackPrimaryParticleTruePositionLeavingTMS: [[  644.8955  -1668.5997  17388.9       779.86926]
 [ 3358.3867  -1221.8699  15584.002     792.6419 ]
 [ 2704.7043   -578.02826 12178.184     780.8086 ]
 [ 1787.4121   -852.3207  12029.962     894.8559 ]]
RecoTrackSecondaryParticlePDG: [         13        -211          13 -1000000000]
RecoTrackSecondaryParticleIndex: [      3192       3194       3192 -999999999]
True Vertex Time: 171.71852
TrueVtxX: 1408.836
TrueVtxY: -3622.9597
TrueVtxZ: 1547.8904

Entry index 6 / 92
Event 441 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: [42]
RecoTrackPrimaryParticlePDG: [13]
RecoTrackPrimaryParticleIndex: [3174]
RecoTrackPrimaryParticleTruePositionLeavingLAr: [[ -504.64603 -1592.4358   9063.763     877.16754]]
RecoTrackPrimaryParticleTruePositionEnteringTMS: [[ -447.45837 -2253.7883  11867.5       886.7791 ]]
RecoTrackPrimaryParticleTruePositionLeavingTMS: [[ -406.79562 -2945.988   14888.054     897.1186 ]]
RecoTrackSecondaryParticlePDG: [-1000000000]
RecoTrackSecondaryParticleIndex: [-999999999]
True Vertex Time: 190.5024
TrueVtxX: 2766.6267
TrueVtxY: -1961.1389
TrueVtxZ: 8087.923

MATCH
RECO_StartPos:  [[ -461.57712 -2123.6584  11177.5      9816.956  ]]
RECO_EndPos:  [[ -403.24667 -2986.0981  14742.5         0.     ]]

RECOTRUE_StartPos: [ -462.32996 -2091.2214  11177.5       884.41376]
RECOTRUE_EndPos: [ -405.59375 -2911.973   14742.5       896.61993]


Entry index 7 / 92
Event 442 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: [48 53]
RecoTrackPrimaryParticlePDG: [13 13]
RecoTrackPrimaryParticleIndex: [3086 3029]
RecoTrackPrimaryParticleTruePositionLeavingLAr: [[-1.8965430e+03 -1.9113022e+03  9.0772275e+03  9.6555505e+02]
 [-1.0000000e+08 -1.0000000e+08 -1.0000000e+08 -1.0000000e+08]]
RecoTrackPrimaryParticleTruePositionEnteringTMS: [[-2268.8032  -1854.4265  11282.5       973.05444]
 [ 3167.9224     44.99108 12316.269    1026.1342 ]]
RecoTrackPrimaryParticleTruePositionLeavingTMS: [[-2144.8882  -1650.2604  13689.435     981.7025 ]
 [ 3403.8884   -483.92365 13507.5      1030.5555 ]]
RecoTrackSecondaryParticlePDG: [-1000000000        2212]
RecoTrackSecondaryParticleIndex: [-999999999       3076]
True Vertex Time: 190.9931
TrueVtxX: 219.22906
TrueVtxY: -3304.5615
TrueVtxZ: -19145.45

Entry index 8 / 92
Event 443 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 285.99118
TrueVtxX: -5201.7573
TrueVtxY: 2305.786
TrueVtxZ: -17625.371

MATCH
RECO_StartPos:  []
RECO_EndPos:  []

RECOTRUE_StartPos: []
RECOTRUE_EndPos: []
No reco track associated with this match


Entry index 9 / 92
Event 444 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: [65 61]
RecoTrackPrimaryParticlePDG: [13 13]
RecoTrackPrimaryParticleIndex: [2955 2985]
RecoTrackPrimaryParticleTruePositionLeavingLAr: [[-1.e+08 -1.e+08 -1.e+08 -1.e+08]
 [-1.e+08 -1.e+08 -1.e+08 -1.e+08]]
RecoTrackPrimaryParticleTruePositionEnteringTMS: [[  -71.87281   246.77267 11559.5      1190.6361 ]
 [ 1584.2716  -2833.0774  15450.503    1140.2107 ]]
RecoTrackPrimaryParticleTruePositionLeavingTMS: [[ -601.8572  -734.0747 14888.83    1202.6886]
 [ 1366.8079 -2591.8022 18477.5     1150.411 ]]
RecoTrackSecondaryParticlePDG: [         13 -1000000000]
RecoTrackSecondaryParticleIndex: [      2935 -999999999]
True Vertex Time: 304.30838
TrueVtxX: 3092.2622
TrueVtxY: -2654.7996
TrueVtxZ: 13631.383

Entry index 10 / 92
Event 445 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: [67]
RecoTrackPrimaryParticlePDG: [13]
RecoTrackPrimaryParticleIndex: [2947]
RecoTrackPrimaryParticleTruePositionLeavingLAr: [[-1.e+08 -1.e+08 -1.e+08 -1.e+08]]
RecoTrackPrimaryParticleTruePositionEnteringTMS: [[ -605.773  -2313.5125 11477.5     1282.1204]]
RecoTrackPrimaryParticleTruePositionLeavingTMS: [[-1119.0707 -2464.9856 18043.15    1304.1179]]
RecoTrackSecondaryParticlePDG: [-1000000000]
RecoTrackSecondaryParticleIndex: [-999999999]
True Vertex Time: 361.8606
TrueVtxX: -2951.8074
TrueVtxY: -3835.303
TrueVtxZ: 21826.904

Entry index 11 / 92
Event 446 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 380.69537
TrueVtxX: -6031.6255
TrueVtxY: -863.81226
TrueVtxZ: 3169.8743

Entry index 12 / 92
Event 447 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: [76]
RecoTrackPrimaryParticlePDG: [13]
RecoTrackPrimaryParticleIndex: [2853]
RecoTrackPrimaryParticleTruePositionLeavingLAr: [[-1.e+08 -1.e+08 -1.e+08 -1.e+08]]
RecoTrackPrimaryParticleTruePositionEnteringTMS: [[  855.8997 -2659.957  12607.863   1406.4459]]
RecoTrackPrimaryParticleTruePositionLeavingTMS: [[  481.2955 -2973.995  15707.863   1416.9241]]
RecoTrackSecondaryParticlePDG: [2212]
RecoTrackSecondaryParticleIndex: [2856]
True Vertex Time: 399.39944
TrueVtxX: -4770.823
TrueVtxY: 267.79468
TrueVtxZ: -178.79306

Entry index 13 / 92
Event 448 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 399.71387
TrueVtxX: -2059.0107
TrueVtxY: -3207.5276
TrueVtxZ: 22261.824

Entry index 14 / 92
Event 449 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 399.76486
TrueVtxX: -3154.6074
TrueVtxY: -424.8685
TrueVtxZ: 16709.58

Entry index 15 / 92
Event 450 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: [92 94]
RecoTrackPrimaryParticlePDG: [-13  13]
RecoTrackPrimaryParticleIndex: [2722 2707]
RecoTrackPrimaryParticleTruePositionLeavingLAr: [[-1162.4974 -1525.1211  8889.612   2020.1775]
 [ 2080.0798  -540.412   8904.177   2014.399 ]]
RecoTrackPrimaryParticleTruePositionEnteringTMS: [[-1107.0511 -1749.028  11380.5     2028.5222]
 [ 2238.1982 -1009.6966 11250.5     2022.461 ]]
RecoTrackPrimaryParticleTruePositionLeavingTMS: [[ -585.6244 -2371.1511 18510.5     2052.4897]
 [ 2381.7073 -1416.964  13227.001   2029.6786]]
RecoTrackSecondaryParticlePDG: [       -211 -1000000000]
RecoTrackSecondaryParticleIndex: [      2701 -999999999]
True Vertex Time: 437.86954
TrueVtxX: -2815.2893
TrueVtxY: -204.81111
TrueVtxZ: -3192.3447

MATCH
RECO_StartPos:  [[-1113.4093 -1747.2632 11177.5        0.    ]
 [ 2241.7673 -1234.5999 11177.5        0.    ]]
RECO_EndPos:  [[ -618.9507 -2367.6438 18502.5        0.    ]
 [ 2321.5    -1133.8616 12997.5        0.    ]]

RECOTRUE_StartPos: [-1111.4493 -1730.9579 11177.5     2027.8422  2234.9434  -994.6877
 11177.5     2022.2102]
RECOTRUE_EndPos: [ -587.07904 -2370.396   18502.5      2052.4624   2325.2444  -1377.6974
 12997.5      2028.6423 ]


Entry index 16 / 92
Event 451 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 456.01978
TrueVtxX: -4040.1753
TrueVtxY: -520.52264
TrueVtxZ: -575.6715

Entry index 17 / 92
Event 452 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 456.3215
TrueVtxX: 4899.2417
TrueVtxY: -799.16315
TrueVtxZ: 21434.486

Entry index 18 / 92
Event 453 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 475.63712
TrueVtxX: 965.3166
TrueVtxY: 756.58704
TrueVtxZ: 13088.542

Entry index 19 / 92
Event 454 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 494.12164
TrueVtxX: -2845.547
TrueVtxY: -3875.2441
TrueVtxZ: 21865.582

Entry index 20 / 92
Event 455 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 494.4869
TrueVtxX: -1086.4436
TrueVtxY: -2572.2197
TrueVtxZ: 12386.027

Entry index 21 / 92
Event 456 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 494.5062
TrueVtxX: -1024.2048
TrueVtxY: 825.7744
TrueVtxZ: 6361.3677

MATCH
RECO_StartPos:  []
RECO_EndPos:  []

RECOTRUE_StartPos: []
RECOTRUE_EndPos: []
No reco track associated with this match


Entry index 22 / 92
Event 457 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 513.9502
TrueVtxX: -1356.011
TrueVtxY: 428.0969
TrueVtxZ: 22732.002

Entry index 23 / 92
Event 458 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 532.95184
TrueVtxX: -2749.1287
TrueVtxY: -6819.2344
TrueVtxZ: 10288.035

Entry index 24 / 92
Event 459 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 608.82794
TrueVtxX: -856.3786
TrueVtxY: 560.6449
TrueVtxZ: -8455.456

MATCH
RECO_StartPos:  []
RECO_EndPos:  []

RECOTRUE_StartPos: []
RECOTRUE_EndPos: []
No reco track associated with this match


Entry index 25 / 92
Event 460 / 6531
Muon Vertex [ 3640.1191    -566.30963  16235.093       19.265991]
RecoTrackPrimaryParticleVtxID: []
RecoTrackPrimaryParticlePDG: []
RecoTrackPrimaryParticleIndex: []
RecoTrackPrimaryParticleTruePositionLeavingLAr: []
RecoTrackPrimaryParticleTruePositionEnteringTMS: []
RecoTrackPrimaryParticleTruePositionLeavingTMS: []
RecoTrackSecondaryParticlePDG: []
RecoTrackSecondaryParticleIndex: []
True Vertex Time: 627.1354
TrueVtxX: -3661.3484

In [14]:
print("Matched TMS indices:", np.array(matched_indices))
#print("Matched Track info:", matched_tracks)

# 1. Convert matched track list to a Pandas DataFrame
matches = pd.DataFrame(matched_tracks, columns=['TMS Truth_Spill ID', 'ND-LAr Matched Particles', 'Time'])

# 2. Clean up the 'Matched Track' column 
# (Turns 'array([1, 2])' into '[1, 2]' for better readability)
matches['ND-LAr Matched Particles'] = matches['ND-LAr Matched Particles'].apply(lambda x: list(x))

# 3. Display the first 50 rows
matches.head(50)

Matched TMS indices: [ 2  6  8 15 21 24 28 29 40 42 44 48 49 67 69 72 74 83 84 92]

,TMS Truth_Spill ID,ND-LAr Matched Particles,Time
0,2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]",76.406227
1,6,"[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 2...",190.502396
2,8,[24],285.991180
3,15,[25],437.869537
4,21,"[26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 3...",494.506195
5,24,"[51, 52, 53, 54]",608.827942
6,28,"[55, 56, 57, 58, 59]",665.226990
7,29,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71]",684.474670
8,40,"[72, 73, 74, 75]",779.915039
9,42,"[76, 77, 78, 79]",836.616760
10,44,"[80, 81, 82]",855.082336
11,48,"[83, 84, 85, 86, 87, 88]",931.563965
12,49,"[89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 1...",969.567383
13,67,[126],1216.233887
14,69,"[127, 128, 129]",1235.837402
15,72,"[130, 131, 132, 133, 134, 135, 136]",1292.125488
16,74,[137],1349.140625
17,83,"[138, 139, 140, 141, 142, 143, 144]",1851.062866
18,84,"[145, 146, 147]",1851.749023
19,92,"[148, 149, 150, 151, 152, 153]",1965.735107

# Setup Figure

In [15]:
def setup_figure(figure, NDLAr_idx):
    figure.update_layout(
        width=1600,
        height=900,
        scene=dict(
            xaxis=dict(title="x [mm]", range=[-4500, 4500]),
            yaxis=dict(title="y [mm]", range=[-4000, 1000]),
            zaxis=dict(title="z [mm]", range=[0, 20000]),
            camera=dict(
                eye=dict(x=2.0, y=4.0, z=0.0),
                up=dict(x=0, y=-1, z=0)           # define Y as "up"
            ),
            aspectmode='manual',
            aspectratio=dict(x=1, y=1, z=4)
        ),
        
        margin=dict(l=0, r=0, b=0, t=50),
        
        showlegend=True,
        legend=dict(
            x=0.02,          # Places legend 2% from the left edge
            y=0.98,          # Places legend 2% from the top edge
            xanchor='left',
            yanchor='top',
            bgcolor='rgba(255, 255, 255, 0.8)', # Semi-transparent white background
            bordercolor='Black',
            borderwidth=1,
            itemsizing='constant'
        ),

        title={
            'text': f"ND-LAr Interaction {NDLAr_idx}",
            'x': 0.5,            # Centers the title
            'xanchor': 'center'
        }
    )
    
    figure.data = []  # Clear all traces
    
    plot_box(figure, -3730, 3730, -3702.23, 997.77, 11177.5, 18502.5, "blue", "TMS detector")
    plot_box(figure, -3478.48, 3478.48, -2166.71, 829.282, 4179.24, 9135.88, "black", "ND-LAr detector")

## Plot ND-LAr event by id

In [16]:
def plot_NDLAr_event(figure, df_parts, df_vtx, indices):
    for idx in indices:
        # 1. Get the target time
        target_time = df_parts.iloc[idx]['Ancestor Time']
        
        # 2. Filter dataframes
        group_parts = df_parts[df_parts['Ancestor Time'] == target_time]
        group_vtx = df_vtx[abs(df_vtx['t'] - target_time) < 1e-5]
    
        # --- Add ALL Tracks (Converting cm -> mm) ---
        x_coords, y_coords, z_coords = [], [], []
        for _, row in group_parts.iterrows():
            # Multiply each coordinate by 10
            x_coords.extend([row['Start Position X']*10, row['End Position X']*10, None])
            y_coords.extend([row['Start Position Y']*10, row['End Position Y']*10, None])
            z_coords.extend([row['Start Position Z']*10, row['End Position Z']*10, None])

    figure.add_trace(
        go.Scatter3d(
            x=x_coords, y=y_coords, z=z_coords,
            mode='lines',
            line=dict(color='darkred', width=3),      # '#e6ab02'
            name=f"ND-LAr Tracks (t={target_time:.3f})",
            hoverlabel_namelength=-1 
        )
    )

    for idx in indices:
        figure.add_trace(
            go.Scatter3d(
                x=truth_interactions[idx].points[:, 0]*10,
                y=truth_interactions[idx].points[:, 1]*10,
                z=truth_interactions[idx].points[:, 2]*10,
                mode="markers",
                marker=dict(size=3, color='#1b9e77'),
                name=f"ND-LAr interaction id {idx}"
            )
        )

        figure.add_trace(
            go.Scatter3d(
                x=truth_particles[idx].points[:, 0]*10,
                y=truth_particles[idx].points[:, 1]*10,
                z=truth_particles[idx].points[:, 2]*10,
                mode="markers",
                marker=dict(size=3, color='black'),
                name=f"ND-LAr particle id {idx}"
            )
        )

    # --- Add ALL Vertices (Converting cm -> mm) ---
    if not group_vtx.empty:
        figure.add_trace(go.Scatter3d(
            # Multiply entire series by 10
            x=group_vtx['Vtx x'] * 10,
            y=group_vtx['Vtx y'] * 10,
            z=group_vtx['Vtx z'] * 10,
            mode='markers',
            marker=dict(size=3, color='red', symbol='x'),
            name=f"True Primary Vertex ND-LAr (t={target_time:.3f})",
            hovertext=[f"ID: {i_id}" for i_id in group_vtx['Interaction id']],
            hoverinfo='text'
        ))

    # --- Layout Update (Units changed to mm) ---
    figure.update_layout(
        title_text=f"Matched Vertex/Ancestor Time: t = {target_time:.3f} &mu;s",
        title_x=0.5,
        margin=dict(t=80, b=20, l=20, r=20),
        scene=dict(
            xaxis_title='X (mm)',
            yaxis_title='Y (mm)',
            zaxis_title='Z (mm)'
        ),
        legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
    )
    
    return target_time

In [17]:
def plot_NDLAr_interaction(figure, idx):
    vtx_x = truth_interactions[idx].vertex[0] * 10
    vtx_y = truth_interactions[idx].vertex[1] * 10
    vtx_z = truth_interactions[idx].vertex[2] * 10
    vtx_t = truth_interactions[idx].t
 
    figure.add_trace(
        go.Scatter3d(
            x=truth_interactions[idx].points[:, 0]*10,
            y=truth_interactions[idx].points[:, 1]*10,
            z=truth_interactions[idx].points[:, 2]*10,
            mode="markers",
            marker=dict(size=2, 
                    color=NDLAr_colour,
                    symbol='circle'
            ),
            name=f"(#{idx}) ND-LAr Hits"
        )
    )

    figure.add_trace(
        go.Scatter3d(
            x = [vtx_x],
            y = [vtx_y],
            z = [vtx_z],
            mode="markers",
            marker=dict(size=4, 
                    color=NDLAr_colour,
                    symbol='square-open'
            ),
            name=f"(#{idx}) ND-LAr Vertex [{vtx_x:.3f}, {vtx_y:.3f}, {vtx_z:.3f}, {vtx_t:.3f}]"
        )
    )

## Plot TMS matches

In [18]:
def plot_TMS_matches(figure, truth_info_idx, truth_spill_idx):
    if truth_info_idx != -1:
        for i, info_idx in enumerate(truth_info_idx, start=0):
            info_time = TMS.NeutrinoX4[info_idx][3]
            #print("TMS Truth_Info time: ", info_time)
    
            neutrino_x, neutrino_y, neutrino_z = [TMS.NeutrinoX4[info_idx][0]], [TMS.NeutrinoX4[info_idx][1]], [TMS.NeutrinoX4[info_idx][2]]
    
            figure.add_trace(go.Scatter3d(
                x=neutrino_x, y=neutrino_y, z=neutrino_z,
                mode='markers',
                marker=dict(
                    size=5,
                    color=strong_colours[i],
                    symbol='circle-open'
                ),
                #name=f'TMS True Hits (t={target_time:.3f})'
                name=f'(#{info_idx}) TMS Truth_Info Vertex [{TMS.NeutrinoX4[info_idx][0]:.3f}, {TMS.NeutrinoX4[info_idx][1]:.3f}, {TMS.NeutrinoX4[info_idx][2]:.3f}, {info_time:.3f}]',
                hoverlabel_namelength=-1 
            ))
            
            hits_x = (TMS.TrueHitX[info_idx])
            hits_y = (TMS.TrueHitY[info_idx])    
            hits_z = (TMS.TrueHitZ[info_idx])
        
            figure.add_trace(go.Scatter3d(
                x=hits_x, y=hits_y, z=hits_z,
                mode='markers',
                marker=dict(
                    size=2,
                    color=light_colours[i],
                    symbol='circle'
                ),
                #name=f'TMS True Hits (t={target_time:.3f})'
                name=f'(#{info_idx}) TMS Truth_Info Hits',
                hoverlabel_namelength=-1 
            ))

    if truth_spill_idx != -1:
        for j, spill_idx in enumerate(truth_spill_idx, start=0):
            spill_time = TMS.TrueVtxT[spill][spill_idx]
            #print("TMS Truth_Spill time:", spill_time)
    
            col = 'black'
            
            if truth_info_idx != -1:
                for m, time_match in enumerate(truth_info_idx, start=0):
                    if abs(spill_time - TMS.NeutrinoX4[truth_info_idx[m]][3]) < 1e-3:
                        col = strong_colours[m]
            
            figure.add_trace(go.Scatter3d(
                x=[TMS.TrueVtxX[spill][spill_idx]], y=[TMS.TrueVtxY[spill][spill_idx]], z=[TMS.TrueVtxZ[spill][spill_idx]],
                mode='markers',
                marker=dict(
                    size=5,
                    color=col,
                    symbol='cross',
                ),
                #name=f'TMS True Hits (t={target_time:.3f})'
                name=f'(#{spill_idx}) TMS Truth_Spill Vertex [{TMS.TrueVtxX[spill][spill_idx]:.3f}, {TMS.TrueVtxY[spill][spill_idx]:.3f}, {TMS.TrueVtxZ[spill][spill_idx]:.3f}, {spill_time:.3f}]',
                hoverlabel_namelength=-1 
            ))

    return figure

## Mapping between ND-LAr and the two TMS truth trees

In [19]:
def get_TMS_indices(df, NDLAr_idx): # Filter the dataframe where NDLAr_idx matches
    row = df[df['NDLAr_idx'] == NDLAr_idx]

    if not row.empty:
        # Access the values (using .iloc[0] to get the first match found)
        info_idx = row['Info_idx'].iloc[0]
        spill_idx = row['Spill_idx'].iloc[0]
        return info_idx, spill_idx
    else:
        return None, None

In [20]:
print("Nof ND-LAr truth interactions:", len(truth_interactions))
print("Nof TMS Truth Info events:", len(TMS.EventNo))
print("Nof TMS Truth Spill events:", len(TMS.TrueVtxT[spill]))

#print(TMS.EventNo)
#print(TMS.EventNo_TruthSpill)
#print(TMS_indices)

matched_data = []
time_window = 1e-3

for NDLAr_idx in range(len(truth_interactions)):
    NDLAr_time = truth_interactions[NDLAr_idx].t - (1.2e9 * spill)
    NDLAr_itx_id = truth_interactions[NDLAr_idx].interaction_id
    
    TMS_info_match = []
    TMS_info_idx_match = []
    TMS_info_prim_pid = []
    TMS_info_sec_pid = []

    TMS_spill_match = []
    TMS_spill_idx_match = []

    for TMS_info_idx in TMS_indices:
        #if NDLAr_idx == 0:
            #print(TMS.NeutrinoX4[TMS_info_idx][3])
        if abs(TMS.NeutrinoX4[TMS_info_idx][3] - NDLAr_time) < time_window:
            TMS_info_match.append(TMS.NeutrinoX4[TMS_info_idx][3])
            TMS_info_idx_match.append(TMS_info_idx)
            TMS_info_prim_pid.append(TMS.RecoTrackPrimaryParticleIndex[TMS_info_idx])
            TMS_info_sec_pid.append(TMS.RecoTrackSecondaryParticleIndex[TMS_info_idx])
    for TMS_spill_idx in range(len(TMS.TrueVtxT[spill])):
        if abs(TMS.TrueVtxT[spill][TMS_spill_idx] - NDLAr_time) < time_window:
            TMS_spill_match.append(TMS.TrueVtxT[spill][TMS_spill_idx])
            TMS_spill_idx_match.append(TMS_spill_idx)
            #print(f"NDLAr: {NDLAr_idx}, TMS_Spill: {TMS_spill_match_idx}")
    
    # Store results in a dictionary
    entry = {
        "NDLAr_idx": NDLAr_idx,
        "NDLAr_time": NDLAr_time,
        "NDLAr_interaction_id": NDLAr_itx_id,
        "Info_idx": TMS_info_idx_match if TMS_info_match else -1,    # Store -1 if no match was found
        "Info_time": TMS_info_match if TMS_info_match else -1,
        "Info_prim_pid": TMS_info_prim_pid if TMS_info_match else -1,
        "Info_sec_pid": TMS_info_sec_pid if TMS_info_match else -1,
        "Spill_idx": TMS_spill_idx_match if TMS_spill_match else -1,
        "Spill_time": TMS_spill_match if TMS_spill_match else -1,
    }
    matched_data.append(entry)

# Create the DataFrame
matches = pd.DataFrame(matched_data)
#matches['Info_idx'] = matches['Info_idx'].astype("Int64")
#matches['Spill_idx'] = matches['Spill_idx'].astype("Int64")

pd.set_option('display.max_rows', None)
matches

Nof ND-LAr truth interactions: 86
Nof TMS Truth Info events: 1234
Nof TMS Truth Spill events: 435

,NDLAr_idx,NDLAr_time,NDLAr_interaction_id,Info_idx,Info_time,Info_prim_pid,Info_sec_pid,Spill_idx,Spill_time
0,0,190.502403,24710000000,-1,-1,-1,-1,[6],[190.5024]
1,1,494.506181,24710000001,-1,-1,-1,-1,[21],[494.5062]
2,2,684.474673,24710000002,-1,-1,-1,-1,[29],[684.4747]
3,3,855.082319,24710000003,-1,-1,-1,-1,[44],[855.08234]
4,4,969.567374,24710000004,-1,-1,-1,-1,[49],[969.5674]
5,5,1851.062917,24710000006,-1,-1,-1,-1,[83],[1851.0629]
6,6,2003.030335,24710000007,-1,-1,-1,-1,[94],[2003.0304]
7,7,2136.083174,24710000008,-1,-1,-1,-1,[98],[2136.0833]
8,8,2421.392313,24710000009,-1,-1,-1,-1,[114],[2421.3923]
9,9,2953.519672,24710000011,[23],[2953.5198],[[]],[[]],[134],[2953.5198]
10,10,3493.338728,24710000013,-1,-1,-1,-1,[155],[3493.3386]
11,11,3569.400392,24710000014,-1,-1,-1,-1,[158],[3569.4004]
12,12,3607.460106,24710000015,[30],[3607.4602],[[2119]],[[2140]],[161],[3607.4602]
13,13,3664.943716,24710000016,-1,-1,-1,-1,[163],[3664.9436]
14,14,4253.182284,24710000017,-1,-1,-1,-1,[188],[4253.182]
15,15,4595.624610,24710000019,[41],[4595.6245],[[1763]],[[-999999999]],[206],[4595.6245]
16,16,6104.698196,24710000020,-1,-1,-1,-1,[271],[6104.698]
17,17,6180.637131,24710000021,[57],[6180.637],[[]],[[]],[278],[6180.637]
18,18,6465.665563,24710000022,-1,-1,-1,-1,[286],[6465.6655]
19,19,6872.699267,24710000023,-1,-1,-1,-1,[303],[6872.699]
20,20,6986.440820,24710000024,-1,-1,-1,-1,[306],[6986.441]
21,21,7917.658636,24710000025,-1,-1,-1,-1,[353],[7917.6587]
22,22,8989.830812,24710000026,-1,-1,-1,-1,[394],[8989.831]
23,23,9578.540043,24710000027,-1,-1,-1,-1,[413],[9578.54]
24,24,4177.109583,1000008710000432,-1,-1,-1,-1,[183],[4177.1094]
25,25,7632.953039,1000008710001446,-1,-1,-1,-1,[339],[7632.953]
26,26,836.616748,1000008710001916,[6],[836.61676],[[3174]],[[-999999999]],[42],[836.61676]
27,27,4861.708326,1000008710002257,-1,-1,-1,-1,[221],[4861.7085]
28,28,1965.735084,1000008710002331,[15],[1965.7351],"[[2722, 2707]]","[[2701, -999999999]]",[92],[1965.7351]
29,29,6522.745070,1000008710003235,-1,-1,-1,-1,[288],[6522.745]
30,30,5078.767354,1000008710003590,[46],[5078.7676],[[]],[[]],[226],[5078.7676]
31,31,285.991180,1000008710003655,-1,-1,-1,-1,[8],[285.99118]
32,32,1216.233917,1000008711000766,[10],[1216.2339],[[2947]],[[-999999999]],[67],[1216.2339]
33,33,3219.966159,1000008711003518,-1,-1,-1,-1,[143],[3219.966]
34,34,9597.070310,1000008711003605,-1,-1,-1,-1,[415],[9597.07]
35,35,7537.354404,1000008712000328,-1,-1,-1,-1,[332],[7537.3545]
36,36,8088.034699,1000008712000970,[79],[8088.0347],[[552]],[[-999999999]],[360],[8088.0347]
37,37,3740.300273,1000008712001250,[31],[3740.3003],[[2089]],[[-999999999]],[164],[3740.3003]
38,38,6579.186749,1000008712001558,-1,-1,-1,-1,[291],[6579.1865]
39,39,5800.897268,1000008712001604,[55],[5800.8975],[[1313]],[[1339]],[257],[5800.8975]
40,40,437.869526,1000008712001748,-1,-1,-1,-1,[15],[437.86954]
41,41,3474.222621,1000008712001749,-1,-1,-1,-1,[152],[3474.2227]
42,42,5097.677710,1000008712002730,[47],[5097.6777],[[]],[[]],[228],[5097.6777]
43,43,779.915060,1000008712002813,-1,-1,-1,-1,[40],[779.91504]
44,44,2953.235174,1000008712003187,-1,-1,-1,-1,[133],[2953.235]
45,45,5553.396742,1000008713002003,-1,-1,-1,-1,[242],[5553.397]
46,46,4329.254470,1000008713002401,-1,-1,-1,-1,[191],[4329.2544]
47,47,3379.108545,1000008713002934,-1,-1,-1,-1,[146],[3379.1086]
48,48,7917.703097,1000008713003225,-1,-1,-1,-1,[354],[7917.703]
49,49,608.827913,1000008713003452,-1,-1,-1,-1,[24],[608.82794]
50,50,6161.644289,1000008714000120,[58],[6161.6445],[[1162]],[[2119]],[277],[6161.6445]
51,51,4937.785004,1000008714000731,[45],[4937.785],[[]],[[]],[223],[4937.785]
52,52,5078.059081,1000008714000910,-1,-1,-1,-1,[225],[5078.059]
53,53,4690.826200,1000008714001327,[43],[4690.826],[[1714]],[[-999999999]],[212],[4690.826]
54,54,6199.863635,1000008714002360,-1,-1,-1,-1,[282],[6199.864]
55,55,1851.749018,1000008714003123,-1,-1,-1,-1,[84],[1851.749]
56,56,1292.125539,1000008714003685,[11],[1292.1255],[[]],[[]],[72],[1292.1255]
57,57,9882.073660,1000008715000503,[92],[9882.073],[[26]],[[-999999999]],[431],[9882.073]
58,58,665.226978,1000008715002955,-1,-1,-1,-1,[28],[665.227]
59,59,6123.191001,1000008715003549,-1,-1,-1,-1,[273],[6123.191]
60,60,76.406223,1000008716000007,[1],[76.40623],[[3565]],[[-999999999]],[2],[76.40623]
61,61,1349.140655,1000008716000587,-1,-1,-1,-1,[74],[1349.1406]
62,62,6104.554332,1000008716000627,-1,-1,-1,-1,[270],[6104.554]
63,63,9141.493614,1000008716001237,[86],[9141.493],[[266]],[[-999999999]],[401],[9141.493]
64,64,7252.599615,1000008716001856,-1,-1,-1,-1,[317],[7252.5996]
65,65,9540.961667,1000008716002373,[87],[9540.962],"[[156, 191]]","[[100, 146]]",[411],[9540.962]
66,66,1235.837354,1000008716002722,-1,-1,-1,-1,[69],[1235.8374]
67,67,5762.305228,1000008717000785,-1,-1,-1,-1,[251],[5762.305]
68,68,7746.499128,1000008717001214,-1,-1,-1,-1,[347],[7746.499]
69,69,5610.078862,1000008717001665,[53],[5610.079],[[1377]],[[-999999999]],[247],[5610.079]
70,70,7366.636585,1000008717001890,-1,-1,-1,-1,[325],[7366.6367]
71,71,8164.658958,1000008717002532,-1,-1,-1,-1,[362],[8164.659]
72,72,6218.567923,1000008717003080,[59],[6218.568],"[[1111, 1123]]","[[-999999999, -999999999]]",[283],[6218.568]
73,73,8419.318018,1000008717003401,[81],[8419.318],[[477]],[[-999999999]],[367],[8419.318]
74,74,3029.832380,1000008718000111,-1,-1,-1,-1,[135],[3029.8323]
75,75,7746.309219,1000008718000202,[75],[7746.309],[[660]],[[-999999999]],[346],[7746.309]
76,76,4424.847126,1000008718000239,[39],[4424.847],[[]],[[]],[197],[4424.847]
77,77,6066.432626,1000008718000551,-1,-1,-1,-1,[268],[6066.4326]
78,78,9293.844468,1000008718001029,-1,-1,-1,-1,[406],[9293.845]
79,79,6853.852637,1000008718001031,-1,-1,-1,-1,[301],[6853.8525]
80,80,931.563941,1000008718002997,-1,-1,-1,-1,[48],[931.56396]
81,81,9502.557210,1000008719000168,-1,-1,-1,-1,[410],[9502.558]
82,82,2820.744353,1000008719000477,-1,-1,-1,-1,[127],[2820.7444]
83,83,4177.844209,1000008719001628,-1,-1,-1,-1,[184],[4177.844]
84,84,6815.175579,1000008719001729,-1,-1,-1,-1,[298],[6815.176]
85,85,3398.329734,1000008719002122,-1,-1,-1,-1,[147],[3398.3298]

## Draw Figure

In [21]:
@interact(NDLAr_idx=(0, len(truth_interactions)-1))
def update_plot(NDLAr_idx):
    fig = go.Figure()

    setup_figure(fig, NDLAr_idx)
    plot_NDLAr_interaction(fig, NDLAr_idx)
    
    idx_info, idx_spill = get_TMS_indices(matches, NDLAr_idx)
    plot_TMS_matches(fig, idx_info, idx_spill)
    
    fig.show()

interactive(children=(IntSlider(value=42, description='NDLAr_idx', max=85), Output()), _dom_classes=('widget-i…